export default [
    "Deep voice",
    "Crisp Voice", 
    "Airy words (stoned)",
    "Repeats last word PC said",
    "Replaces vowels with 'a's (a as in apple)",
    "Australia",
    "Authoritative",
    "Meek",
    "Baby voice",
    "Battlecruiser (Starcraft)",
    "British",
    "Bro",
    "Brooklyn",
    "Clicks their tongue",
    "Danny DeVito",
    "Mumbles 'dododo...' a lot",
    "Flamboyant",
    "French",
    "German",
    "Ghost (Starcraft)",
    "Forest Gump",
    "Just punched in the gut",
    "High pitched",
    "Japanese",
    "New Zealand",
    "Liquid U's ",
    "Lisp","Low pitched",
    "Just had their mind blown",
    "Minnesota (Fargo)",
    "Says 'mmm' a lot",
    "Like mouth is full",
    "Nasally",
    "No Accent",
    "Out of breath",
    "Awkward Pauses",
    "Pirate",
    "Their Race",
    "Rugged",
    "Russian",
    "Scottish",
    "Stuffed Nose",
    "Snake-like",
    "Southern Drawl",
    "Stretches 'oo's",
    "Period after every word",
    "Strained (constipated)",
    "Stutters",
    "Surfer dude",
    "Don't let tongue touch bottom or top of mouth",
    "Tony Tiger (don't extend r's)",
    "Winnie the Pooh",
    "Wiseguy",
    "Valley girl",
    "Posh aristocrat",
    "Robot-like monotone",
    "Eastern European",
    "Bostonian",
    "Italian",
    "Texan",
    "Irish",
    "Latin American",
    "English",
    "Elderly",
    "Gothic and brooding",
    "Old-timey radio announcer",
    "Heavy smoker",
    "Military drill sergeant",
    "Opera singer",
    "Sleepy and slow",
    "Auctioneer speed talker",
    "Mimics every sound",
    "Smooth jazz singer",
    "Swedish Chef (Muppets)",
    "Excitedly",
    "Canadian",
    "Dramatic Shakespearean",
    "Tired",
    "Dutch",
    "The Godfather",
    "Grizzled",
    "Elvis impersonator",
    "Stereotypical nerd",
    "Snorts alot",
    "Sound of cleaning teeth with tongue",
    "A wording crouch, ya see, ya see!",
    "Yoda speak they do",
    "Whispery",
    "LOUD AND BOISTEROUS",
    "Pauses....mid-sentence (Christopher Walken)",
    "Pauses....throughout...sentence (William Shatner)",
    "Super monotone, laughs without smiling",
    "Stops after every sentence, never know when they're done talking",
    "Speaks like an AC-TOR",
    "Smacks and purses lips a lot",
    "Runs sentences together",
    "Out the corner of their mouth",
    "Speaks through clenched teeth",
    "Your mouth as closed as possible",
    "Your mouth as wide open as possible",
    "Keep tongue pressed on bottom of mouth",
    "Keep tongue pressed behind teeth",
    "Every sentence is a question",
    "Clicks tongue",
    "Way too much hand movement",
    "Only use proper nouns",
    "Rhymes Constantly",
    "Non-stop puns",
    "Uses condescending nicknames",
    "Always begins with 'So, like...'",
    "Pick a letter to over emphasize",
]
