export default [
    "Deep voice",
    "Crisp Voice", 
    "Airy words (stoned)",
    "Repeats last word PC said",
    "Replaces vowels with 'a's (a as in apple)",
    "Australia","Authoritative",
    "Baby voice",
    "Battlecruiser (Starcraft)",
    "British",
    "Bro",
    "Brooklyn",
    "Clicks their tongue",
    "Danny DeVito",
    "Mumbles 'dododo...' a lot",
    "Flamboyant",
    "French",
    "German",
    "Ghost (Starcraft)",
    "Forest Gump",
    "Just punched in the gut",
    "High pitched",
    "Japanese",
    "New Zealand ",
    "Liquid U's ",
    "Lisp","Low pitched",
    "Just had their mind blown",
    "Minnesota (Fargo)",
    "Says 'mmm' a lot",
    "Morty",
    "Like mouth is full",
    "Nasally",
    "None",
    "Out of breath",
    "Awkward Pauses",
    "Pirate",
    "Their Race",
    "Rugged",
    "Russian",
    "Scottish",
    "Stuffed Nose",
    "Snake-like",
    "Southern Drawl",
    "Stretches 'oo's",
    "Period after every word",
    "Strained (constipated)",
    "Stutters",
    "Surfer dude",
    "Don't let tongue touch bottom or top of mouth",
    "Tony Tiger (don't extend r's)",
    "Winnie the Pooh",
    "Wiseguy",
    "Valley girl",
    "Posh aristocrat",
    "Robot-like monotone",
    "Eastern European",
    "Bostonian",
    "Italian",
    "Texan cowboy",
    "Sassy teenager",
    "Whiny tone",
    "Irish",
    "Elderly person",
    "Excited child",
    "Gothic and brooding",
    "Old-timey radio announcer",
    "Heavy smoker",
    "Hyperactive chipmunk",
    "Military drill sergeant",
    "Opera singer",
    "Hesitant thinker",
    "Sleepy and slow",
    "Growling predator",
    "Auctioneer speed talker",
    "Storytelling grandparent",
    "Mimics every sound",
    "Jovial jester",
    "Sarcastic skeptic",
    "Over-the-top evil villain",
    "Melodramatic actor",
    "Polite but condescending",
    "Outspoken protester",
    "Zen monk",
    "Pop singer autotuned",
    "Southern Belle",
    "Viking",
    "Ghetto",
    "Transatlantic",
    "Southern Gentleman",
    "Cajun",
    "Yodeling",
    "Gibberish",
    "Stuttering professor",
    "New York City",
    "High Society",
    "Californian",
    "Angry neighbor",
    "Smooth jazz singer",
    "Swedish Chef (Muppets)",
    "Excited game show host",
    "Surly mechanic",
    "Frantic scientist",
    "French Canadian",
    "Dramatic Shakespearean",
    "Dude from a beach movie",
    "Tired old man",
    "Hawaiian surfer",
    "Country bumpkin",
    "Dutch",
    "Spooky ghost",
    "Preppy college student",
    "Cheerleader",
    "Surfer dude",
    "Don't let tongue touch bottom or top of mouth",
    "Tony Tiger (don't extend r's)",
    "Winnie the Pooh",
    "Wiseguy",
    "Valley girl",
    "Posh aristocrat",
    "Robot-like monotone",
    "Eastern European",
    "Bostonian",
    "Italian",
    "Texan cowboy",
    "Sassy teenager",
    "Whiny tone",
    "Irish",
    "Elderly person",
    "Excited child",
    "Gothic and brooding",
    "Old-timey radio announcer",
    "Heavy smoker",
    "Deep voice",
    "Crisp Voice", 
    "Airy words (stoned)",
    "Repeats last word back",
    "Replaces vowels with 'a's (a as in apple)",
    "Australia","Authoritative",
    "Baby voice",
    "Battlecruiser (Starcraft)",
    "British",
    "Bro",
    "Brooklyn",
    "Clicks their tongue",
    "Danny DeVito",
    "Mumbles 'dododo...' a lot",
    "Flamboyant",
    "French",
    "German",
    "Ghost (Starcraft)",
    "Forest Gump",
    "Just punched in the gut",
    "High pitched",
    "Japanese",
    "New Zealand ",
    "Liquid U's ",
    "Lisp","Low pitched",
    "Just had their mind blown",
    "Minnesota (Fargo)",
    "Says 'mmm' a lot",
    "Morty",
    "Like mouth is full",
    "Nasally",
    "None",
    "Out of breath",
    "Awkward Pauses",
    "Pirate",
    "Their Race",
    "Rugged",
    "Russian",
    "Scottish",
    "Stuffed Nose",
    "Snake-like",
    "Southern Drawl",
    "Stretches 'oo's",
    "Period after every word",
    "Strained (constipated)",
    "Skeptical lawyer",
    "Underwater bubble speech",
    "French aristocrat",
    "Hipster",
    "Hick",
    "Disgruntled employee",
    "Sassy older woman",
    "The Godfather",
    "Unimpressed teenager",
    "Villainous mastermind",
    "Childish and whiny",
    "Slick salesman",
    "Nasally New York",
    "British Cockney",
    "Lazy lounge singer",
    "Eccentric inventor",
    "Grizzled detective",
    "Hyper salesperson",
    "Curious tourist",
    "Eagle Scout",
    "Dramatic opera character",
    "Southern farm boy",
    "Elvis impersonator",
    "Exaggerated valley accent",
    "Arrogant businessman",
    "Clumsy scientist",
    "Surprised tourist",
    "Lumberjack",
    "Stereotypical nerd",
    "Shy introvert",
    "Cheerful grandmother",
    "Macho action hero",
    "Space explorer",
    "Pretentious artist",
    "Mysterious wanderer",
    "Wacky scientist",
    "Childlike wonder",
    "Chipper receptionist",
    "Goth teenager",
    "Dorky professor",
    "Sleep-deprived parent",
    "Snorts alot",
    "High pitched granny",
    "Sound of cleaning teeth with tongue",
    "British posh ( potato in the mouth style)",
    "A wording crouch, ya see, ya see!",
    "Yoda speak they do",
    "super whisper all the time",
    "LOUD AND BOISTEROUS LAUGHING SOMETIMES AS WELL",
    "Pauses....mid-sentence (Christopher Walken)",
    "Pauses....throughout...sentence (William Shatner)",
    "Repeats last word they said, said",
    "Super monotone, laughs without smiling",
    "Stops after every sentence, never telegraphing when they're done talking",
    "Speaks like an AC-TOR: super overexaggerated",
    "Smacks and purses lips at odd point in the sentence",
    "Runs sentences together",
    "Only speaks out of the corner of their mouth",
    "Speaks through clenched teeth",
    "Has a severe underbite or overbite",
    "Speak with your mouth as closed as possible",
    "Keep tongue pressed on bottom of mouth/behind bottom teeth.",
    "Every sentence is a question",
    "Clicks tongue",
    "Stereotyped Scandanavian ",
    "Way too much hand movement",
    "Only use proper nouns",
    "Rhymes Constantly",
    "Non-stop puns",
    "Constantly using condescending nicknames",
    "Begins every statement with 'So, like...'",
    "Pick a letter to over emphasize",
]
