const appearance = [
    "Afro Hair",
    "Animal Feature",
    "Baggy Eyes",
    "Practicing Balance",
    "Bald",
    "Bandana",
    "Belts with metal hoops",
    "Biting Lip",
    "Biting nails",
    "Bracelets",
    "Braided Hair",
    "Broad Shoulders",
    "Bucktooth",
    "Burns",
    "Bushy eyebrows",
    "Button Nose",
    "Camouflage",
    "Cape",
    "Ceramic Mask",
    "Chubby",
    "Collar",
    "Colorful Hair",
    "Curly Hair",
    "Dark Skin",
    "Dimple",
    "Discolored Skin",
    "Dreadlocks",
    "Dry skin",
    "Long Earrings",
    "Earmuffs",
    "Expensive Clothing",
    "Eyepatch",
    "Face Paint",
    "Family Crest patch",
    "Fangs",
    "Fashionably Dressed",
    "Fidgety",
    "Flat hat",
    "Food on face",
    "Smells oddly nice",
    "Gloves",
    "Goggles",
    "Gown",
    "Gross teeth",
    "Hollow Eyes",
    "Horns",
    "Large Forehead",
    "Long Face",
    "Long Fingernails",
    "Long Fingers",
    "Long Hair",
    "Long Limbs",
    "Long Nose",
    "Loose Clothing",
    "Meaty Lips",
    "Missing Arm",
    "Missing Leg",
    "Narrow Eyes",
    "Narrow Shoulders",
    "Obese",
    "Oily skin",
    "Old",
    "Pale Skin",
    "Pantless",
    "Pelt Coat",
    "Picking Nose",
    "Piercing Eyes",
    "Piercings",
    "Pimples",
    "Plain Face",
    "Pointy Hat",
    "Pony Tail",
    "Puffy Pants",
    "Rags",
    "Robes",
    "Scarcely Dressed",
    "Scars",
    "Scruffy facial hair",
    "Shirtless",
    "Short",
    "Extremely Skinny",
    "Sleeveless Shirt",
    "Smooth Hands",
    "Spits",
    "Stiff Clothes",
    "Stinks",
    "Stubby Limbs",
    "Tall",
    "Tan Skin",
    "Tattoos",
    "Thick facial hair",
    "Thin Lips",
    "Tight Clothing",
    "Torn Clothing",
    "Tunic",
    "Whiskers",
    "Wide Eyes",
    "Wooden Mask",
    "Wool Hat",
    "Woolen clothing",
    "Warn Hands",
    "Young",
    "athletic",",
    "beautiful",
    "blotchy",
    "brawny",
    "bronzed",
    "burly",
    "frail",
    "fragile",
    "gangly",
    "gaunt",
    "gawky",
    "haggard",
    "hideous",
    "lanky",
    "lifeless",
    "lithe",
    "muscular",
    "overweight",
    "pallid",
    "veiny",
    "pasty",
    "plump",
    "puny",
    "rangy",
    "scarred",
    "skeletal",
    "slender",
    "slight",
    "statuesque",
    "stocky",
    "strapping",
    "trim",
    "voluptuous",
    "weak",
    "willowy",
    "wiry",
    "wrinkled",
    "scrawny",
    "herculean",
    "athletic",
    "burly",
    "chubby",
    "compact",
    "gangly",
    "gaunt",
    "heavyset",
    "lanky",
    "lithe",
    "muscular",
    "petite",
    "scrawny",
    "skinny",
    "slender",
    "slight",
    "solid",
    "statuesque",
    "stocky",
    "strapping",
    "thin",
    "willowy",
    "battle-scarred",
    "blood-stained",
    "dimpled",
    "freckled",
    "swollen",
    "toothless",
    "slobbering",
    "frothing",
    "frostbitten",
    "regal",
    "bald",
    "braided",
    "curly",
    "dishevelled",
    "greasy",
    "rosy",
    "tear-stained",
    "Attractive",
    "Beautiful",
    "Charming",
    "Cute",
    "Elegant",
    "Glamorous",
    "Handsome",
    "Lovely",
    "Classy",
    "Dapper",
    "Dashing",
    "debonair",
    "Dressed up",
    "Exquisite",
    "Fine-looking",
    "Foxy",
    "Good-looking",
    "Gorgeous",
    "Graceful",
    "Ideal",
    "Immaculate",
    "Magnificent",
    "Neat",
    "Neat-looking",
    "Nice-looking",
    "Perfect",
    "Pleasant",
    "Polished",
    "Radiant",
    "Refined",
    "Sharp",
    "Sophisticated",
    "Stunning",
    "Stylish",
    "Superb",
    "Symmetrical",
    "Tasteful",
    "Trim",
    "Well-groomed",
    "Well-dressed",
"Afro Hair",
"Animal Feature",
"Baggy Eyes",
"Practicing Balance",
"Bald",
"Bandana",
"Belts with metal hoops",
"Biting Lip",
"Biting nails",
"Bracelets",
"Braided Hair",
"Broad Shoulders",
"Bucktooth",
"Burns",
"Bushy eyebrows",
"Button Nose",
"Camouflage",
"Cape",
"Ceramic Mask",
"Chubby",
"Collar",
"Colorful Hair",
"Curly Hair",
"Dark Skin",
"Dimple",
"Discolored Skin",
"Dreadlocks",
"Dry skin",
"Long Earrings",
"Earmuffs",
"Expensive Clothing",
"Eyepatch",
"Face Paint",
"Family Crest patch",
"Fangs",
"Fashionably Dressed",
"Fidgety",
"Flat hat",
"Food on face",
"Smells oddly nice",
"Gloves",
"Goggles",
"Gown",
"Gross teeth",
"Hollow Eyes",
"Horns",
"Large Forehead",
"Long Face",
"Long Fingernails",
"Long Fingers",
"Long Hair",
"Long Limbs",
"Long Nose",
"Loose Clothing",
"Meaty Lips",
"Missing Arm",
"Missing Leg",
"Narrow Eyes",
"Narrow Shoulders",
"Obese",
"Oily skin",
"Old",
"Pale Skin",
"Pantless",
"Pelt Coat",
"Picking Nose",
"Piercing Eyes",
"Piercings",
"Pimples",
"Plain Face",
"Pointy Hat",
"Pony Tail",
"Puffy Pants",
"Rags",
"Robes",
"Scarcely Dressed",
"Scars",
"Scruffy facial hair",
"Shirtless",
"Short",
"Extremely Skinny",
"Sleeveless Shirt",
"Smooth Hands",
"Spits",
"Stiff Clothes",
"Stinks",
"Stubby Limbs",
"Tall",
"Tan Skin",
"Tattoos",
"Thick facial hair",
"Thin Lips",
"Tight Clothing",
"Torn Clothing",
"Tunic",
"Whiskers",
"Wide Eyes",
"Wooden Mask",
"Wool Hat",
"Woolen clothing",
"Warn Hands",
"Young",
"athletic",
"beautiful",
"blotchy",
"brawny",
"bronzed",
"burly",
"frail",
"fragile",
"gangly",
"gaunt",
"gawky",
"haggard",
"hideous",
"lanky",
"lifeless",
"lithe",
"muscular",
"overweight",
"pallid",
"veiny",
"pasty",
"plump",
"puny",
"rangy",
"scarred",
"skeletal",
"slender",
"slight",
"statuesque",
"stocky",
"strapping",
"trim",
"voluptuous",
"weak",
"willowy",
"wiry",
"wrinkled",
"scrawny",
"herculean",
"athletic",
"burly",
"chubby",
"compact",
"gangly",
"gaunt",
"heavyset",
"lanky",
"lithe",
"muscular",
"petite",
"scrawny",
"skinny",
"slender",
"slight",
"solid",
"statuesque",
"stocky",
"strapping",
"thin",
"willowy",
"battle-scarred",
"blood-stained",
"dimpled",
"freckled",
"swollen",
"toothless",
"slobbering",
"frothing",
"frostbitten",
"regal",
"bald",
"braided",
"curly",
"dishevelled",
"greasy",
"rosy",
"tear-stained",
"Attractive",
"Beautiful",
"Charming",
"Cute",
"Elegant",
"Glamorous",
"Handsome",
"Lovely",
"Classy",
"Dapper",
"Dashing",
"debonair",
"Dressed up",
"Exquisite",
"Fine-looking",
"Foxy",
"Good-looking",
"Gorgeous",
"Graceful",
"Ideal",
"Immaculate",
"Magnificent",
"Neat",
"Neat-looking",
"Nice-looking",
"Perfect",
"Pleasant",
"Polished",
"Radiant",
"Refined",
"Sharp",
"Sophisticated",
"Stunning",
"Stylish",
"Superb",
"Symmetrical",
"Tasteful",
"Trim",
"Well-groomed",
"Well-dressed",
"Sharp Jawline", "Cleft Chin", "Freckled Nose", "Sharp Cheeks", "Pointed Ears", "Angular Features", "Sloped Shoulders", "Bony Hands", "High Cheekbones", "Wide Shoulders", "Thick Neck", "Sharp Nose", "Wide Jaw", "Beady Eyes", "Broad Jaw", "Square Chin", "Small Ears", "Shimmering Skin", "Graceful Movements", "Radiant Smile", "Pale Lips", "Narrow Nose", "Plump Cheeks", "Soft Hands", "Soft Skin", "Faint Scars", "Sweaty Skin", "Veiny Hands", "Hairy Arms", "Shaky Hands", "Large Hands", "Hollow Cheeks", "Lush Eyebrows", "Defined Eyebrows", "Short Neck", "Teeth Gap", "Pale Lips", "Deep-set Eyes", "Wet Hair", "Strawberry Blonde Hair", "Silver Hair", "Wild Hair", "Chiseled Features", "Fuzzy Skin", "Glossy Hair", "Long Eyelashes", "Pockmarked Skin", "Rough Skin", "Hairless Legs", "Shimmering Eyes", "Bushy Beard", "Full Beard", "Clean-shaven", "Pointy Teeth", "Thin Frame", "Unkempt Hair", "Wide Lips", "Glowing Complexion", "Faint Freckles", "Shy Smile", "Puffy Cheeks", "Tall Stature", "Slender Neck", "Full Lips", "Exotic Eyes", "Aged Skin",  "Slouching Posture", "Thick Eyelashes", "Lumpy Skin", "Stocky Build", "Wrinkled Hands", "Glistening Skin", "Hollow Neck", "Unusual Hair Color", "Textured Hair", "Shiny Lips", "Large Feet", "Flushed Skin", "Distinctive Mole", "Rough Hands", "Toned Abdomen", "Healthy Nails", "Dimples on Cheeks", "Slight Hunch", "Distinctive Nose Shape", "Hunched Shoulders", "Brilliant Eyes", "Golden Hair", "Flawless Skin", "Faint Scars on Arms", "Broad Torso", "Muscular Arms", "Lopsided Smile", "Chubby Cheeks", "Curvy Frame", "Strong Jawline", "Solid Posture", "Flushed Cheeks", "Rough Hair", "Plump Nose", "Sweaty Forehead", "Silky Hair", "Large Frame", "Freckled Arms", "Shaggy Hair", "Sharp Look", "Freckled Shoulders", "Slightly Crooked Teeth", "Sharp Fingernails", "Fair Skin", "Flawless Face", "Rough Elbows", "Fine Hair Texture", "Full Face", "Sharp Eyebrows", "Dazzling Smile",
"Glittery Skin",
"Uneven Tan",
"Cracked Fingernails",
"Faint Glow",
"Shadowy Aura",
"Frosty Eyebrows",
"Dusty Clothing",
"Translucent Skin",
"Soot-Streaked Face",
"Scorched Clothing",
"Prickly Stubble",
"Golden Irises",
"Stained Fingertips",
"Frosted Hair Ends",
"Smudged Eyeliner",
"Rusty Jewelry",
    "Bone-Crested Armor",
    "Feather-Lined Scarf",
    "Scaled Leather Jacket",
    "Glowing Symbol Robes",
    "Smoky Edged Cloak",
    "Clock-Topped Hat",
    "Transparent Sole Shoes",
    "Wolf Buckle Belt",
    "Chainmail Sleeve Shirt",
    "Star Map Gloves",
    "Wood-Heeled Boots",
    "Pocketed Patchwork Cape",
    "Gear Necklace Pendant",
    "Glittering Veil Hat",
    "Sparking Metal Bracelets",
    "Moon Shaped Earrings",
    "Glow-Stitched Shirt",
    "Crying Face Mask",
    "Coiled Snake Ring",
    "Dragon Wing Sashes",
    "Liquid Core Pendant",
    "Color-Shifting Fur",
    "Rotating Lens Goggles",
    "Lantern Choker Necklace",
    "Spiderweb Pattern Gloves",
    "Candle Helmet Crown",
    "Soft Chiming Sandals",
    "Vine Woven Belt",
    "Billowing Windless Cape",
    "River Designed Robes",
    "Key Charm Bracelet",
    "Glitter Trail Bag",
    "Thorn Crown Circlet",
    "Starlit Sky Shawl",
    "Woven Leaf Suit",
    "Sword Brooch Pin",
    "Waterfall Draped Hood",
    "Bird Wing Shoulderpads",
    "Metallic Thread Cloak",
    "Gear Motif Vest",
    "Gem-Lit Helmet",
    "Sparkling Movement Shoes",
    "Dancing Figure Suspenders",
    "Coiled Dragon Bracelet",
    "Frozen Flame Pendant",
    "Bone Button Shirt",
    "Spiraling Flame Cloak",
    "Soft Glow Ring",
    "Color-Changing Gloves",
    "Geometric Shirt Patterns",
    "Hue Shifting Scarf",
    "Fiery Print Boots",
    "Fox Face Mask",
    "Fluttering Feather Hat",
    "Floating Fabric Sash",
    "Hourglass Necklace Chain",
    "Metal Bead Coat",
    "Falling Star Earrings",
    "Deep Pocket Vest",
    "Silver Thread Hat",
    "River Embroidered Robes",
    "Glowing Sole Shoes",
    "Flower Pattern Shirt",
    "Rippled Water Cloak",
    "Encased Flame Pendant",
    "Raindrop Charm Bracelet",
    "Flickering Flame Hat",
    "Gold Stud Gloves",
    "Fish Scale Coat",
    "Ringed Chain Necklace",
    "Ankle Wing Boots",
    "Mismatched Mask Half",
    "Glittering Edge Shawl",
    "Dragon Head Shoulderpad",
    "Metal Ring Shirt",
    "Insect Adorned Bag",
    "Humming Sound Robe",
    "Glass Charm Belt",
    "Bloom Flower Hat",
    "Lightning Stitched Jacket",
    "Silver Stripe Shoes",
    "Compass Ring Ornament",
    "Pattern Changing Scarf",
    "Upward Feather Helmet",
    "Gold Scale Gloves",
    "Warm Pocket Robe",
    "Storm Cloud Pendant",
    "Silent Walking Boots",
    "Bark Pattern Suspenders",
    "Singed Edge Coat",
    "Glowing Crystal Necklace",
    "Expanding Brim Hat",
    "Painted Porcelain Mask",
    "Gemstone Belt Buckle",
    "Mosaic Print Shirt",
    "Shadow Drip Robe",
    "Soft Hum Shawl",
    "Beaded Ribbon Tie",
    "Shadow-Lined Hat",
    "Fur-Edged Gloves",
    "Luminous Thread Coat",
    "Rose Stitched Dress",
    "Cracked Leather Belt",
    "Veil-Embroidered Mask",
    "Stained Glass Cape",
    "Runed Metal Gauntlets",
    "Fringed Satin Scarf",
    "Flame-Wrought Crown",
    "Threadbare Velvet Cloak",
    "Plated Copper Vest",
    "Flickering Gem Earrings",
    "Spiral-Marked Sash",
    "Shadow Trim Boots",
        "Crystal-Woven Cape",
        "Frayed Tapestry Robes",
        "Moonlit Lace Scarf",
        "Ivy-Wrapped Belt",
        "Starburst Patterned Shirt",
        "Velvet Trim Gloves",
        "Frost-Kissed Shawl",
        "Glass Fragment Pendant",
        "Shimmering Chainmail Vest",
        "Bloodstained Edge Cloak",
        "Etched Stone Gauntlets",
        "Rain-Soaked Jacket",
        "Silver-Tipped Boots",
        "Web-Wrapped Hat",
        "Bone-Laced Corset",
        "Fog-Threaded Robes",
        "Rune-Carved Necklace",
        "Driftwood-Lined Sash",
        "Obsidian Stud Gloves",
        "Smoke-Tinted Veil",
        "Charcoal Edged Scarf",
        "Moon Phase Bracelet",
        "Pebbled Leather Belt",
        "Glimmer Dust Cape",
        "Frost-Dipped Sleeves",
        "Glitter-Edged Robes",
        "Coil-Plated Armor",
        "Shadow-Woven Hood",
        "Scorched Edge Cloak",
        "Gold-Flecked Shoes",
        "Leaf-Stitched Gloves",
        "Polished Marble Circlet",
        "Copper-Rimmed Goggles",
        "Wind-Touched Shawl",
        "Meteor Fragment Pendant",
        "Ripple-Patterned Vest",
        "Crimson Thread Cloak",
        "Jagged Steel Pauldron",
        "Velvet-Lined Hat",
        "Beaded Leaf Necklace",
        "Glow-Woven Scarf",
        "Quilted Satin Cape",
        "Gilded Feather Crown",
        "Bronze-Lined Bracers",
        "Sunlit Ray Cloak",
        "Ember-Kissed Gloves",
        "Prismatic Belt Buckle",
        "Twisting Thorn Sash",
        "Lava-Threaded Hood",
        "Silhouette Print Shirt",
        "Enchanted Vine Hat",
        "Shattered Glass Circlet",
        "Driftwood-Laced Gloves",
        "Fog-Touched Poncho",
        "Gem-Flecked Vest",
        "Loom-Woven Cloak",
        "Sparked Flame Boots",
        "Sealed Wax Belt",
        "Feather-Draped Robes",
        "Polished Steel Mask",
        "Sand-Dusted Cape",
        "Coal-Tinted Cloak",
        "Dew-Laden Shawl",
        "Steel-Bound Armlets",
        "Velvet-Streaked Coat",
        "Shadow-Fringed Scarf",
        "Crystal Embedded Mask",
        "Iridescent Wing Shawl",
        "Coiled Rope Belt",
        "Slate-Lined Sandals",
        "Gold-Spun Scarf",
        "Twilight Cloak Pins",
        "Lichen-Draped Sash",
        "Oil-Slick Gloves",
        "Silver-Lined Trousers",
        "Drip-Stained Cape",
        "Rune-Patterned Helm",
        "Flowing Shadow Robes",
        "Blazing Edge Hood",
        "Starfall Pendant",
        "Frost-Laced Mittens",
        "Glint-Tipped Shoes",
        "Rusted Chain Scarf",
        "Sapphire-Rimmed Goggles",
        "Blossom-Adorned Belt",
        "Seashell Necklace Pendant",
        "Veil-Lined Bracers",
        "Thorn-Laced Boots",
        "Ripple-Wrought Circlet",
        "Flame-Edged Crown",
        "Etched Spiral Gloves",
        "Cloud-Woven Robes",
        "Silver-Tipped Armbands",
        "Bronze-Studded Mask",
        "Stained Ink Shawl",
        "Dagger-Patterned Belt",
        "Crystal-Lit Brooch",
        "Ivy-Trimmed Collar",
        "Pebble-Dusted Vest",
        "Faintly Glowing Gauntlets",
        "Star-Laced Hood",
        "Dawn-Kissed Scarf",
        "River-Stitched Gloves",
        "Solar Fragment Pendant",
        "Frosted Gold Cuffs",
        "Polished Ebony Sash",
        "Moon-Touched Belt",
        "Obsidian-Lined Vest",
        "Rainbow-Threaded Cloak",
        "Twisting Root Gloves",
        "Crackling Spark Ring",
        "Shadow-Loomed Boots"
        ];
        