const rawAppearance = [
    "Afro Hair",
    "Animal Feature",
    "Baggy Eyes",
    "Practicing Balance",
    "Bald",
    "Bandana",
    "Belts with metal hoops",
    "Biting Lip",
    "Biting nails",
    "Bracelets",
    "Braided Hair",
    "Broad Shoulders",
    "Bucktooth",
    "Burns",
    "Bushy eyebrows",
    "Button Nose",
    "Camouflage",
    "Cape",
    "Ceramic Mask",
    "Chubby",
    "Collar",
    "Colorful Hair",
    "Curly Hair",
    "Dimple",
    "Discolored Skin",
    "Dreadlocks",
    "Dry skin",
    "Long Earrings",
    "Earmuffs",
    "Expensive Clothing",
    "Eyepatch",
    "Face Paint",
    "Family Crest patch",
    "Fangs",
    "Fashionably Dressed",
    "Fidgety",
    "Flat hat",
    "Food on face",
    "Smells oddly nice",
    "Gloves",
    "Goggles",
    "Gown",
    "Gross teeth",
    "Hollow Eyes",
    "Horns",
    "Meaty Lips",
    "Missing Arm",
    "Missing Leg",
    "Narrow Eyes",
    "Narrow Shoulders",
    "Obese",
    "Bright eyes",
    "Old",
    "Pale Skin",
    "Pantless",
    "Pelt Coat",
    "Picking Nose",
    "Piercing Eyes",
    "Piercings",
    "Pimples",
    "Plain Face",
    "Pointy Hat",
    "Pony Tail",
    "Puffy Pants",
    "Rags",
    "Robes",
    "Scarcely Dressed",
    "Scars",
    "Scruffy facial hair",
    "Shirtless",
    "Short",
    "Extremely Skinny",
    "Sleeveless Shirt",
    "Smooth Hands",
    "Spits",
    "Stiff Clothes",
    "Stinks",
    "Stubby Limbs",
    "Tall",
    "Tan Skin",
    "Tattoos",
    "Tattooed Face",
    "Thick facial hair",
    "Thin Lips",
    "Tight Clothing",
    "Torn Clothing",
    "Tunic",
    "Whiskers",
    "Wide Eyes",
    "Wooden Mask",
    "Wool Hat",
    "Woolen clothing",
    "Warn Hands",
    "Young",
    "athletic",
    "beautiful",
    "blotchy",
    "brawny",
    "bronzed",
    "burly",
    "frail",
    "fragile",
    "gangly",
    "gaunt",
    "gawky",
    "haggard",
    "hideous",
    "lanky",
    "lifeless",
    "lithe",
    "muscular",
    "overweight",
    "pallid",
    "veiny",
    "pasty",
    "plump",
    "puny",
    "rangy",
    "scarred",
    "skeletal",
    "slender",
    "slight",
    "statuesque",
    "stocky",
    "strapping",
    "trim",
    "voluptuous",
    "weak",
    "willowy",
    "wiry",
    "wrinkled",
    "scrawny",
    "herculean",
    "athletic",
    "burly",
    "chubby",
    "compact",
    "gangly",
    "gaunt",
    "heavyset",
    "lanky",
    "lithe",
    "muscular",
    "petite",
    "scrawny",
    "skinny",
    "slender",
    "slight",
    "solid",
    "statuesque",
    "stocky",
    "strapping",
    "thin",
    "willowy",
    "battle-scarred",
    "blood-stained",
    "dimpled",
    "freckled",
    "swollen",
    "toothless",
    "slobbering",
    "frothing",
    "frostbitten",
    "regal",
    "bald",
    "braided",
    "curly",
    "dishevelled",
    "greasy",
    "rosy",
    "tear-stained",
"Afro Hair",
"Animal Feature",
"Baggy Eyes",
"Practicing Balance",
"Bald",
"Bandana",
"Biting Lip",
"Biting nails",
"Bracelets",
"Braided Hair",
"Broad Shoulders",
"Bucktooth",
"Burns",
"Bushy eyebrows",
"Button Nose",
"Camouflage",
"Cape",
"Ceramic Mask",
"Chubby",
"Collar",
"Colorful Hair",
"Curly Hair",
"Dimple",
"Discolored Skin",
"Dreadlocks",
"Dry skin",
"Earmuffs",
"Expensive Clothing",
"Eyepatch",
"Face Paint",
"Family Crest patch",
"Fangs",
"Fidgety",
"Flat hat",
"Food on face",
"Gloves",
"Goggles",
"Gown",
"Gross teeth",
"Hollow Eyes",
"Horns",
"Large Forehead",
"Long Face",
"Long Fingernails",
"Long Fingers",
"Long Hair",
"Long Limbs",
"Long Nose",
"Loose Clothing",
"Meaty Lips",
"Missing Arm",
"Missing Leg",
"Narrow Eyes",
"Narrow Shoulders",
"Obese",
"Oily skin",
"Old",
"Pale Skin",
"Pantless",
"Pelt Coat",
"Picking Nose",
"Piercing Eyes",
"Piercings",
"Pimples",
"Plain Face",
"Pointy Hat",
"Pony Tail",
"Puffy Pants",
"Rags",
"Robes",
"Scarcely Dressed",
"Scars",
"Scruffy facial hair",
"Shirtless",
"Short",
"Extremely Skinny",
"Sleeveless Shirt",
"Smooth Hands",
"Spits",
"Stiff Clothes",
"Stinks",
"Stubby Limbs",
"Tall",
"Tan Skin",
"Tattoos",
"Thick facial hair",
"Thin Lips",
"Tight Clothing",
"Torn Clothing",
"Tunic",
"Whiskers",
"Wide Eyes",
"Wooden Mask",
"Wool Hat",
"Woolen clothing",
"Warn Hands",
"Young",
"athletic",
"beautiful",
"blotchy",
"brawny",
"bronzed",
"burly",
"frail",
"fragile",
"gangly",
"gaunt",
"gawky",
"haggard",
"hideous",
"lanky",
"lifeless",
"lithe",
"muscular",
"overweight",
"pallid",
"veiny",
"pasty",
"plump",
"puny",
"rangy",
"scarred",
"skeletal",
"slender",
"slight",
"statuesque",
"stocky",
"strapping",
"trim",
"voluptuous",
"weak",
"willowy",
"wiry",
"wrinkled",
"scrawny",
"herculean",
"athletic",
"burly",
"chubby",
"compact",
"gangly",
"gaunt",
"heavyset",
"lanky",
"lithe",
"muscular",
"petite",
"scrawny",
"skinny",
"slender",
"slight",
"solid",
"statuesque",
"stocky",
"strapping",
"thin",
"willowy",
"battle-scarred",
"blood-stained",
"dimpled",
"freckled",
"swollen",
"toothless",
"frothing",
"frostbitten",
"regal",
"bald",
"braided",
"curly",
"dishevelled",
"greasy",
"rosy",
"tear-stained",
"Attractive",
"Beautiful",
"Charming",
"Cute",
"Elegant",
"Glamorous",
"Handsome",
"Lovely",
"Classy",
"Dapper",
"Dashing",
"debonair",
"Dressed up",
"Exquisite",
"Foxy",
"Good-looking",
"Gorgeous",
"Graceful",
"Ideal",
"Immaculate",
"Magnificent",
"Neat",
"Perfect",
"Pleasant",
"Polished",
"Radiant",
"Refined",
"Sharp",
"Sophisticated",
"Stunning",
"Stylish",
"Superb",
"Symmetrical",
"Tasteful",
"Trim",
"Well-groomed",
"Well-dressed",
"Sharp Jawline", "Cleft Chin", "Freckled Nose", "Sharp Cheeks", "Pointed Ears", "Angular Features", "Sloped Shoulders", "Bony Hands", "High Cheekbones", "Wide Shoulders", "Thick Neck", "Sharp Nose", "Wide Jaw", "Beady Eyes", "Broad Jaw", "Square Chin", "Small Ears", "Shimmering Skin", "Graceful Movements", "Radiant Smile", "Pale Lips", "Narrow Nose", "Plump Cheeks", "Soft Hands", "Soft Skin", "Faint Scars", "Sweaty Skin", "Veiny Hands", "Hairy Arms", "Shaky Hands", "Large Hands", "Hollow Cheeks", "Lush Eyebrows", "Defined Eyebrows", "Short Neck", "Teeth Gap", "Pale Lips", "Deep-set Eyes", "Wet Hair", "Strawberry Blonde Hair", "Silver Hair", "Wild Hair", "Chiseled Features", "Fuzzy Skin", "Glossy Hair", "Long Eyelashes", "Pockmarked Skin", "Rough Skin", "Hairless Legs", "Shimmering Eyes", "Bushy Beard", "Full Beard", "Clean-shaven", "Pointy Teeth", "Thin Frame", "Unkempt Hair", "Wide Lips", "Glowing Complexion", "Faint Freckles", "Shy Smile", "Puffy Cheeks", "Tall Stature", "Slender Neck", "Full Lips", "Exotic Eyes", "Aged Skin",  "Slouching Posture", "Thick Eyelashes", "Lumpy Skin", "Stocky Build", "Wrinkled Hands", "Glistening Skin", "Hollow Neck", "Unusual Hair Color", "Textured Hair", "Shiny Lips", "Large Feet", "Flushed Skin", "Distinctive Mole", "Rough Hands", "Toned Abdomen", "Healthy Nails", "Dimples on Cheeks", "Slight Hunch", "Distinctive Nose Shape", "Hunched Shoulders", "Brilliant Eyes", "Golden Hair", "Flawless Skin", "Faint Scars on Arms", "Broad Torso", "Muscular Arms", "Lopsided Smile", "Chubby Cheeks", "Curvy Frame", "Strong Jawline", "Solid Posture", "Flushed Cheeks", "Rough Hair", "Plump Nose", "Sweaty Forehead", "Silky Hair", "Large Frame", "Freckled Arms", "Shaggy Hair", "Sharp Look", "Freckled Shoulders", "Slightly Crooked Teeth", "Sharp Fingernails", "Fair Skin", "Flawless Face", "Rough Elbows", "Fine Hair Texture", "Full Face", "Sharp Eyebrows", "Dazzling Smile",
"Uneven Tan",
"Cracked Fingernails",
"Faint Glow",
"Shadowy Aura",
"Frosty Eyebrows",
"Dusty Clothing",
"Translucent Skin",
"Sooty",
"Scorched Clothing",
"Prickly Stubble",
"Golden Irises",
"Stained Fingertips",
"Frosted Hair Ends",
"Smudged Eyeliner",
"Rusty Jewelry",
"Sunken Cheeks",
"Sunburned Skin",
"Calloused Hands",
"Calloused Fingers",
"Jagged Scars",
"Crooked Nose",
"Crooked Smile",
"Broad Hips",
"Narrow Hips",
"Strong Shoulders",
"Sloping Forehead",
"Angular Jaw",
"Round Face",
"Square Face",
"Wide Nose",
"Heavy Brow",
"Bushy Mustache",
"Thin Mustache",
"Patchy Beard",
"Shaved Head",
"Sideburns",
"Hooked Nose",
"Hook Hand",
"Upturned Nose",
"Pointed Chin",
"Rounded Chin",
"Crooked Teeth",
"Missing Teeth",
"Yellowed Teeth",
"Stained Teeth",
"Rosy Cheeks",
"Dark Circles Under Eyes",
"Heavy Eyelids",
"Arched Eyebrows",
"Thin Eyebrows",
"Prominent Adam's Apple",
"Broad Chest",
"Narrow Chest",
"Thick Arms",
"Thin Arms",
"Knobby Knees",
"Long Legs",
"Short Legs",
"Broad Feet",
"Nimble Fingers",
"Short Fingers",
"Long Toes",
"Tattooed Arms",
"Tattooed Hands",
"Pierced Nose",
"Pierced Eyebrow",
"Pierced Lip",
"Pierced Tongue",
"Five O'clock Shadow",
"Shaved Eyebrows",
"Braided Beard",
"Frizzy Hair",
"Oiled Hair",
"Matted Hair",
"Neatly Combed Hair",
"Short Hair",
"Shoulder-length Hair",
"Side-parted Hair",
"Center-parted Hair",
"Streaked Hair",
"Unkempt Beard",
"Short Beard",
"Long Beard",
"Pointed Beard",
"Tangled Beard",
"Cold Eyes",
"Warm Eyes",
"Squinting Eyes",
"Wide Eyes",
"Partially Closed Eyes",
"Sharp Cheekbones",
"Soft Cheekbones",
"Broad Nose",
"Straight Nose",
"Thick Eyebrows",
"Weathered Face",
"Tired Eyes",
"Sparkling Eyes",
"Broad Smile",
"Thin Smile",
"Dimpled Chin",
"Sunken Eyes",
"Flushed Neck",
"Weather-beaten Skin",
"Calloused Feet",
"Broad Forehead",
"Narrow Forehead",
"Thin Neck",
"Broad Neck",
"Veined Forearms",
"Long Torso",
"Short Torso",
"Stooped Posture",
"Peg leg",
"Layered Clothing",
"Stained Cloak",
"Hooded Cloak",
"Fur-lined Cloak",
"Tattered Cloak",
"Patchwork Cloak",
"Heavy Cloak",
"Simple Cloak",
"Wet Cloak",
"Frayed Sleeves",
"Rolled-up Sleeves",
"Puffy Sleeves",
"Tight Sleeves",
"Loose Sleeves",
"Cuffed Sleeves",
"High Collar",
"Open Collar",
"Stiff Collar",
"Loose Tunic",
"Fitted Tunic",
"Quilted Jacket",
"Long Coat",
"Fur-trimmed Coat",
"Leather Vest",
"Embroidered Robe",
"Wide Belt",
"Rope Belt",
"Sash Belt",
"Studded Belt",
"Fingerless Gloves",
"Leather Gloves",
"Silk Gloves",
"Worn Boots",
"Polished Boots",
"Knee-high Boots",
"Heavy Boots",
"Sandals",
"Barefoot",
"Patterned Socks",
"Patchy Trousers",
"Baggy Trousers",
"Tight Trousers",
"Muddy Pants",
"Short Skirt",
"Long Skirt",
"Apron",
"Stained Apron",
"Tool Belt",
"Shoulder Cape",
"Hooded Shawl",
"Woolen Shawl",
"Silk Scarf",
"Wool Scarf",
"Tied Headscarf",
"Wide-brimmed Hat",
"Feathered Hat",
"Shiny Jewelry",
"Beaded Necklace",
"Pendant Necklace",
"Layered Necklaces",
"Metal Bracelets",
"Beaded Bracelets",
"Anklet",
"Rings",
"Gem-set Ring",
"Pinned Brooch",
"Decorative Buttons",
"Mismatched Buttons",
"Colorful Sash",
"Crossbody Strap",
"Padded Shoulders",
"Sturdy Overalls",
"Stained Overalls",
"Overstuffed Pockets",
"Neatly Pressed Clothing",
"Wrinkled Clothing",
"Clashing Colors",
"Monochrome Outfit",
"Colorful Outfit",
"Faded Fabrics",
"Freshly Mended Clothing",
"Torn Hems",
"Frayed Edges",
"Pinned Medallion",
"Tool-laden Harness",
"Tribal Tattoo",
"Geometric Tattoo",
"Floral Tattoo",
"Animal Tattoo",
"Arcane Tattoo",
"Scarred Face",
"Wooden Eye",
"Leg Brace",
"Arm Sling",
"Crutch",
"Cane",
"Top Hat",
"Bowler Hat",
"Ear Muffs",
"Visor",
"Monocle",
"Pocket Watch",
"Gauntlets",
"Spurs",
"Medallion",
"Signet Ring",
"Embroidered Handkerchief",
"Locket",
"Feathered Clothes",
"Crown",
"Tiara",
"Dyed Hair",
"Gold Teeth",
"Guages",
"Cat Ears",
"Glasses",
"Goggles",

];

const appearance = [];
const seen = new Set();

for (const entry of rawAppearance) {
    const key = entry.toLowerCase();
    if (!seen.has(key)) {
        seen.add(key);
        appearance.push(entry);
    }
}

export default appearance;
        