export default [
    "Has a Family",
    "Well-Traveled",   
    "Orphaned",
    "Former Soldier",
    "Noble Birth",
    "Famous Artist",
    "Outlaw",
    "Exiled",
    "Scholar",
    "Merchant",
    "Farm Raised",
    "Street Urchin",
    "Religious Leader",
    "Widowed",
    "Prisoner",
    "Survivor of Disaster",
    "Reformed Criminal",
    "Betrayed by a Friend",
    "Raised by Animals",
    "Wanderer",
    "Village Elder",
    "Apprentice",
    "Child Prodigy",
    "Immigrant",
    "Bounty Hunter",
    "Spy",
    "Former Royal Guard",
    "Adventurer",
    "Pirate",
    "Revolutionary",
    "Healer",
    "Ruler",
    "Fugitive",
    "Fallen Hero",
    "Scholar of the Occult",
    "Lonely Wanderer",
    "Con Artist",
    "Teacher",
    "Explorer",
    "Craftsman",
    "Historian",
    "War Veteran",
    "Tragic Loss",
    "Mystic",
    "Famous Performer",
        "Ex-Gladiator",
        "Former Spy",
        "Royal Servant",
        "Merchant’s Heir",
        "Rogue Scholar",
        "Rescued from the Wild",
        "Former Assassin",
        "Haunted by the Past",
        "Seafaring Captain",
        "Crusader",
        "Mountain Hermit",
        "Ex-Courtier",
        "Bard’s Apprentice",
        "Tribal Warrior",
        "Disowned by Family",
        "Abandoned at Birth",
        "Revenge Seeker",
        "Reclusive Inventor",
        "Mysterious Stranger",
        "Witch’s Apprentice",
        "Scholar of Forbidden Arts",
        "Slave Turned Free",
        "Sellsword",
        "Warlock’s Disciple",
        "Former Gladiator",
        "Former Royalty",
        "Forbidden Love",
        "Family of Healers",
        "Noble Assassin",
        "Exiled Priest",
        "Shunned by Society",
        "Knight’s Apprentice",
        "Tinker",
        "Amnesiac",
        "Weathered Survivor",
        "Shipwreck Survivor",
        "Fallen Noble",
        "Family of Scholars",
        "Champion of a Cause",
        "Vengeful Spirit",
        "Secretive Cult Member",
        "Master of a Guild",
        "Betrayer",
        "Pirate’s Offspring",
        "Tragic Betrayal",
        "Exiled Thief",
        "Nomadic Tribe Member",
        "Rural Artisan",
        "Famous Explorer",
        "Child of a Prodigy",
        "Last of a Line",
        "Cursed",
        "Abandoned Soldier",
        "Nomad",
        "Soldier Turned Farmer",
        "Murderer Seeking Redemption",
        "Master of Disguise",
        "Bastard Child",
        "Famed Diplomat",
        "Prophet’s Disciple",
        "Herbalist",
        "Princess in Hiding",
        "Orphaned Noble",
        "Renegade Knight",
        "Magical Outcast",
        "Bounty Hunter’s Apprentice",
        "Hunted by a Shadow",
        "Torn Between Two Worlds",
        "Highwayman",
        "Infiltrator",
        "Forbidden Knowledge Seeker",
        "Acclaimed Poet",
        "Ex-Merchant",
        "Survivor of War",
        "Lonely Seeker",
        "Underground Fighter",
        "Defector",
        "Exiled Sorcerer",
        "Treasure Hunter",
        "Underdog",
        "Bandit Leader",
        "Returned from the Dead",
        "Diplomat’s Child",
        "City Watch Member",
        "Royal Architect",
        "Caretaker of Sacred Grounds",
        "Beastmaster",
        "Tavern Keeper",
        "Vagrant",
        "Dream Interpreter",
        "Old Soldier",
        "Hunter Gatherer",
        "Mountain Guide",
        "Forgotten Heir",
        "Master Craftsman",
        "Bastion of the Old Ways",
        "Whistleblower",
        "Reformed Pirate",
        "Adopted by Nobles",
        "Survivor of a Plague",
        "Cursed Wanderer",
        "Forsaken Lover",
        "Lone Survivor",
        "Gambling Addict",
        "Genius Inventor",
        "Retired Gladiator",
        "Town Magistrate",
        "Rogue Noble",
        "Exiled Sorcerer",
        "Trainee Spy",
        "Betrayed Knight",
        "Escaped Slave",
        "Exiled Princess",
        "Reformed Bandit",
        "Champion of the Arena",
        "Sentimental Wanderer",
        "Disillusioned Soldier",
        "Druid’s Heir",
        "Mountain Outcast",
        "Fallen Priest",
        "Renegade Monk",
        "Wildland Protector",
        "Royal Spy",
        "Mysterious Healer",
        "Wayward Noble",
        "Secret Revolutionary",
        "Doomed Prophet",
        "Nomadic Teacher",
        "Warrior of the Old Order",
        "Hidden Heir",
        "Survivor of the Abyss",
        "Loyal Servant",
        "Forsaken by the Gods",
        "Shady Merchant",
        "Hidden Witness",
        "Untrustworthy Informant",
        "Royal Bodyguard",
        "Criminal Undercover",
        "Knight of the Realm",
        "Fabled Legend",
        "Elder of the Tribe",
        "The Last of Their Kind",
            "Once a Royal Advisor",
            "Former Gladiator Champion",
            "Exiled from the Kingdom",
            "Once a Trusted Bodyguard",
            "Once a Renowned Hunter",
            "Former Pirate Captain",
            "Used to be a Wandering Bard",
            "Was a Diplomatic Envoy",
            "Once a Mercenary Leader",
            "Former War Hero",
            "Once a Court Magician",
            "Was the Youngest Noble",
            "Previously a Slave in a Foreign Land",
            "Once Trained as a Scribe",
            "Once an Assassination Target",
            "Once the Head of a Merchant Guild",
            "Exiled for a Betrayal",
            "Was an Initiate of a Forbidden Cult",
            "Used to Be a Village Elder",
            "Once a Rebel Leader",
            "Previously a Street Performer",
            "Once a Wealthy Landowner",
            "Was a High-Ranking Priest",
            "Previously a Legendary Pirate",
            "Once a Hired Spy",
            "Had a Reputation as a Duelist",
            "Once an Outlaw Leader",
            "Once an Expert in the Occult",
            "Used to Be a Famous Explorer",
            "Was the King's Heir",
            "Once a Legendary Beast Slayer",
            "Previously a Champion Wrestler",
            "Was a Trusted Informant",
            "Once a Renowned Sculptor",
            "Had a Career as a Soldier of Fortune",
            "Was a Gladiator in the Arena",
            "Once a Knight in Service to the Crown",
            "Was a Renowned Druid of the Forest",
            "Used to be a Respected Scholar",
            "Once a Member of a Thieves' Guild",
            "Previously a Successful Ship Captain",
            "Once a Hidden Noble",
            "Once a Master Falconer",
            "Was the Head of a Renowned School",
            "Once a Healer to the Royals",
            "Used to be a Mercenary in the Wars",
            "Once a Court Jester",
            "Was a Legendary Swordfighter",
            "Once a Famous Architect",
            "Was a Famous Poet in the Courts",
            "Once a Member of a Secret Society",
            "Used to Be a Diplomat for the Empire",
            "Was a Cursed Noble",
            "Once Trained in Ancient Martial Arts",
            "Had a Career as an Undercover Agent",
            "Once a Captive of Pirates",
            "Previously a Mentor to Young Warriors",
            "Was a Renowned Merchant in Foreign Lands",
            "Once a Soldier of the Great War",
            "Was an Outcast from a Prestigious Family",
            "Once a Cursed Treasure Hunter",
            "Used to Be a Monk in a Remote Temple",
            "Once a Guardian of Sacred Relics",
            "Had a Reputation as a Master Tracker",
            "Was a Shipwreck Survivor",
            "Once an Assassin for the Guild",
            "Was a Secretly Hunted Fugitive",
            "Used to Be a Nomadic Leader",
            "Once a Nomadic Trader",
            "Was a Blacksmith's Apprentice",
            "Previously a Famous Alchemist",
            "Once a Renowned Beast Tamer",
            "Used to Be a Monk of the Mountain Order",
            "Once a Sage in a Remote Village",
            "Was an Apprentice to a Powerful Wizard",
            "Was a Former Royal Spy",
            "Once a Sought-After Diplomatic Mediator",
            "Used to Be a Court Inventor",
            "Once a Renowned Musician",
            "Was a King's General",
            "Previously a Respected Hunter",
            "Was an Exiled Court Official",
            "Once a High-Ranking Thief",
            "Had a Career as an Underground Fighter",
            "Once the Head of an Assassin's Guild",
            "Was a Skilled Craftsman in a Distant Land",
            "Once a Member of the Royal Guard",
            "Had a Reputation as a Fierce War Chief",
            "Used to Be a Royal Seamstress",
            "Once a Famous Astronomer",
            "Was a Champion in Ancient Games",
            "Once the Leader of a Crusade",
            "Had a Past as a Hired Thief",
            "Once a Highly Regarded Noble Diplomat",
            "Was a Legendary Wrestler in the Courts",
            "Once a Famous Gladiator",
            "Used to Be a Respected Sorcerer",
            "Was a Mercenary of a Fallen Kingdom",
            "Once a Reformed Criminal",
            "Was a Protector of the Sacred Grove",
            "Had a Life as a Traveling Healer",
            "Once a Herald of the Kingdom",
            "Was a Master of the Art of Forgery",
            "Once a Famous Courtesan",
            "Had a Past as a Hunter of Magical Creatures",
            "Used to Be a Knight of the Lost Order",
            "Once a Mercenary in a Foreign War",
            "Was a Healer in a Plague-Ridden City",
            "Had a Career as a Wild Beast Hunter",
            "Once a Guard to a Legendary Ruler",
            "Once the Captain of a Legendary Ship",
            "Was a Lurking Shadow in the Kingdom",
            "Once an Influential Tribal Leader",
            "Was a Member of an Exiled Royal Family",
            "Had a Past as a Legendary Warrior",
            "Once a Scorned Ex-Princess",
            "Had a Career as an Ancient Relic Hunter",
            "Used to Be a Cult Leader",
            "Once a Watcher of the Sacred Monastery",
            "Was an Heir to a Fallen Kingdom",
            "Once a Healer in a Forgotten Land",
            "Used to Be a Legendary Gladiator Champion",
            "Once a Famous Spymaster",
            "Was the Last of an Ancient Line",
            "Had a Reputation as a Master of Shadows",
            "Once an Agent of a Fallen Empire",
            "Was a Protector of the Sacred Temple",
            "Had a Life as a Reclusive Scholar",
            "Once a Trusted Captain of a Fleet",
            "Was a Trusted Assassin for Hire",
            "Had a Past as an Expert Tracker",
            "Once a Famous Beast Hunter",
            "Was a Nomad in the Great Desert",
            "Once the Right Hand to a King",
            "Had a Career as a Hidden Informant",
            "Once a Legendary Monk of the Order",
            "Was a Famed Strategist in Wars",
            "Used to Be a Master Thief",
            "Once a Loyal Servant of the Empire",
            "Had a Career as an Exiled Warrior",
                "Once a Village Blacksmith",
                "Had a Job as a Farmer",
                "Used to Be a Tavern Worker",
                "Worked as a Fisherman",
                "Was a Merchant's Assistant",
                "Once a Guard at the City Gates",
                "Was a Carpenter's Apprentice",
                "Had a Life as a Stablehand",
                "Worked as a Seamstress",
                "Was a Baker’s Apprentice",
                "Once a Town Errand Boy",
                "Had a Job as a Town Crier",
                "Used to Be a Cartographer",
                "Once a Shopkeeper",
                "Worked as a Delivery Person",
                "Was a Stablemaster",
                "Had a Job as a Town Watchman",
                "Once a Farmhand",
                "Used to Be a Librarian",
                "Once a Traveling Merchant",
                "Was a Simple Tailor",
                "Had a Job as a Stable Boy",
                "Once a Waiter in a Busy Tavern",
                "Worked as a Glassblower",
                "Once a Candle Maker",
                "Was a Town Fisher",
                "Worked as a Woodcutter",
                "Once a Simple Cook",
                "Had a Job as a Street Sweeper",
                "Once an Apprentice to a Mason",
                "Worked as a Soap Maker",
                "Used to Be a Milkman",
                "Once a Barmaid",
                "Was a Miner's Assistant",
                "Had a Career as a Paper Peddler",
                "Was a Locksmith’s Apprentice",
                "Used to Be a Postman",
                "Once a Street Vendor",
                "Had a Job as a Silversmith",
                "Was a Barrel Maker",
                "Once a Shoe Cobbler",
                "Worked as a Town Porter",
                "Had a Job as a Coin Collector",
                "Used to Be a Rope Maker",
                "Once a Town Gardener",
                "Worked as a Water Carrier",
                "Had a Job as a Barber",
                "Used to Be a Housekeeper",
                "Once a Candle Maker’s Assistant",
                "Worked as a Butcher’s Apprentice",
                "Was a Town Mechanic",
                "Had a Job as a Flower Seller",
                "Once a Town Clerk",
                "Worked as a Sweeper in the Market",
                "Used to Be a Herbalist’s Helper",
                "Once a Clerk in a Shop",
                "Had a Job as a Cartwright",
                "Was a Roofer’s Apprentice",
                "Once a Warehouse Manager",
                "Used to Be a Shepherd",
                "Had a Job as a Rope Maker’s Assistant",
                "Once a Town Cook",
                "Worked as a Tinker",
                "Was a Peddler in the Market",
                "Once an Apprentice to a Gardener",
                "Had a Career as a Town Porter",
                "Used to Be a Waitstaff at a Fine Inn",
                "Once a Personal Servant",
                "Had a Job as a Cloth Dyer",
                "Worked as a Tavern Cook",
                "Used to Be a Muddy Road Laborer",
                "Was a Merchant’s Apprentice",
                "Once a Town Launderer",
                "Worked as a Market Stall Owner",
                "Had a Job as a Furniture Maker",
                "Once a Grain Merchant",
                "Worked as a Tavern Bouncer",
                "Was a Street Performer for Coins",
                "Had a Job as a Fence Repairman",
                "Once an Apprentice to a Butcher",
                "Worked as a Dry Goods Seller",
                "Used to Be a Fisherman’s Mate",
                "Once a Wool Spinner",
                "Had a Job as a Stable Keeper",
                "Worked as a Town Bartender",
                "Once a Miner",
                "Used to Be a Tailor's Apprentice",
                "Once a Town Shoemaker",
                "Had a Job as a Bread Baker",
                "Worked as a Shoe Repairman",
                "Was a Cart Driver",
                "Once a Barrel Maker’s Assistant",
                "Worked as a Stonecutter",
                "Used to Be a Weaving Assistant",
                "Had a Job as a Town Physician's Assistant",
                "Was a Guard in the Local Arena",
                "Once a Farm Supply Vendor",
                "Worked as a Wool Dyer",
                "Once a Spice Merchant",
                "Had a Job as a Pickpocket",
                "Worked as a Dry Goods Merchant",
                "Once a Saddle Maker’s Assistant",
                "Used to Be a Pigeon Keeper",
                "Once a Town Painter",
                "Had a Job as a Food Vendor",
                "Worked as a Herald’s Assistant",
                "Once a Town Fisherman’s Mate",
                "Had a Job as a Public Notary",
                "Was a Mender of Clothes",
                "Once a Soap Maker's Helper",
                "Worked as a Mud Brick Maker",
                "Once a Horse Groomer",
                "Had a Job as a Plumber",
                "Was a Village Land Surveyor",
                "Used to Be a Water Digger",
                "Had a Career as a Town Woodcarver",
                "Once a Building Contractor",
                "Worked as a Locksmith",
                "Used to Be a Town Tax Collector",
                "Once a Public Works Assistant",
                "Had a Job as a Ragpicker",
                "Worked as a Traveling Errand Boy",
                "Once a Public Scribe",
                "Had a Job as a Firewood Seller",
                "Used to Be a Town Messenger",
                "Once a Cattle Herding Assistant",
                "Had a Job as a Leatherworker",
                "Once a Clockmaker’s Apprentice",
                "Was a Carrier of Firewood",
                "Worked as a Builder's Apprentice",
                "Once a Public Crier",
                "Had a Job as a Town Rebuilder",
                "Used to Be a Bridge Worker",
                "Once a Fishmonger’s Assistant",
                "Had a Job as a Town Administrator",
                "Once a Local Innkeeper",
                "Used to Be a Dairy Farm Helper",
                "Had a Job as a Rope Weaver",
                "Once a Local Woodcarver",
                "Worked as a Traveling Salesman",
                "Once an Organizer of Local Festivals",
                    "Works as a Baker",
                    "Tends a Garden",
                    "Drives a Cart",
                    "Fishes for a Living",
                    "Runs a Tavern",
                    "Shovels Coal",
                    "Cleans Stables",
                    "Tends Sheep",
                    "Mends Clothes",
                    "Works as a Carpenter",
                    "Repairs Shoes",
                    "Serves as a Waiter",
                    "Sells Spices",
                    "Cares for Horses",
                    "Maintains Roads",
                    "Sweeps Streets",
                    "Sells Fruit",
                    "Works as a Tailor",
                    "Hunts Small Game",
                    "Keeps Bees",
                    "Runs a Butcher Shop",
                    "Mends Furniture",
                    "Works as a Seamstress",
                    "Delivers Mail",
                    "Sweeps Chimneys",
                    "Bakes Bread",
                    "Cleans Fish",
                    "Works as a Blacksmith",
                    "Cleans Houses",
                    "Sells Pottery",
                    "Grows Herbs",
                    "Works as a Barber",
                    "Delivers Goods",
                    "Harvests Crops",
                    "Prepares Meals",
                    "Repairs Tools",
                    "Builds Houses",
                    "Sells Wool",
                    "Cleans Stalls",
                    "Catches Birds",
                    "Tends a Dairy Farm",
                    "Repairs Clocks",
                    "Brews Beer",
                    "Cares for Children",
                    "Grows Vegetables",
                    "Works as a Miller",
                    "Sells Clothes",
                    "Repairs Furniture",
                    "Cleans Boots",
                    "Builds Furniture",
                    "Repairs Windows",
                    "Works as a Stonecutter",
                    "Tends a Vineyard",
                    "Works as a Merchant",
                    "Cares for Cattle",
                    "Mends Fences",
                    "Maintains Horses",
                    "Tends to Livestock",
                    "Works as a Chef",
                    "Repairs Pots",
                    "Cleans Stalls",
                    "Sells Grain",
                    "Works as a Farmer",
                    "Repairs Jewelry",
                    "Makes Candles",
                    "Hunts for Food",
                    "Mends Roofs",
                    "Harvests Timber",
                    "Makes Soap",
                    "Repairs Clothes",
                    "Repairs Swords",
                    "Gathers Wood",
                    "Tends to Orchards",
                    "Works as a Gardener",
                    "Works as a Merchant",
                    "Mends Carpets",
                    "Cleans Public Spaces",
                    "Catches Fish",
                    "Repairs Locks",
                    "Tends a Flower Bed",
                    "Works as a Laborer",
                    "Mends Baskets",
                    "Works as a Peddler",
                    "Maintains Taverns",
                    "Tends to Plants",
                    "Builds Shelves",
                    "Mends Clothing",
                    "Sells Ale",
                    "Tends to Pigs",
                    "Makes Cloth",
                    "Delivers Firewood",
                    "Cleans Stables",
                    "Sells Furniture",
                    "Makes Jewelry",
                    "Maintains the Furnace",
                    "Builds Bridges",
                    "Mends Tools",
                    "Catches Rabbits",
                    "Works as a Tanner",
                    "Delivers Meat",
                    "Cleans Public Baths",
                    "Sells Candles",
                    "Makes Pottery",
                    "Repairs Houses",
                    "Repairs Shoes",
                    "Sells Herbs",
                    "Works as a Librarian",
                    "Repairs Locks",
                    "Works as a Painter",
                    "Harvests Apples",
                    "Repairs Leather Goods",
                    "Runs an Inn",
                    "Tends to Crops",
                    "Works as a Fisherman",
                    "Collects Eggs",
                    "Cleans the Town Square",
                    "Sells Baked Goods",
                    "Works as a Guard",
                    "Grows Flowers",
                    "Tends to a Stable",
                    "Works as a Woodcutter",
                    "Sells Candles",
                    "Works as a Weaver",
                    "Tends to Dogs",
                    "Works as a Crier",
                    "Sells Tools",
                    "Works as a Dyer",
                    "Repairs Walls",
                    "Works as a Groomer",
                    "Cleans Stables",
                    "Makes Blankets",
                    "Repairs Sails",
                    "Works as a Peddler",
                    "Sells Soap",
                    "Tends to the Market",
                    "Gathers Herbs",
                    "Mends Rugs",
                    "Works as a Builder",
                    "Makes Potions",
                    "Sells Wood",
                    "Works as a Hunter",
                    "Repairs Dishes",
                    "Works as a Guard",
                    "Builds Stalls",
                    "Tends to the Oven",
                    "Works as a Cook",
                    "Repairs Tents",
                    "Makes Curtains",
                    "Cleans Dishes",
                    "Sells Salt",
                    "Repairs Chairs"
                ];
                
            
        