export default [ "Accountability",
"Civility",
"Cultural Rights",
"Economic Growth",
"Environmental Protection",
"Equality",
"Welfare",
"Peace",
"Violence",
"Privacy",
"Free Movement, Assembly",
"Free Speech",
"Religion",
"Mutual Respect",
"Non-discrimination",
"Reciprocity",
"Responsibility",
"Romance",
"Personal Wealth",
"Safety",
"Children Treated As Adults",
"Obedient",
"Technological Progress",
"Solidarity & Community",
"Truth / Transparency",
"Hard Work",
"Liesure",
"Respect Elders",
"Formality",
"Education",
"Humility",
"Family",
"Honor Above All",
"Might Makes Right",
"Magic Supremacy",
"Technological Rejection",
"Preserve History / Memory",
"Eccentricity Encouraged",
"Sacrifice",
"Perfectionism",
"Glutony",
"Animal Rights",
"Hero Worship",
"Luck as a Measure of Worth",
"Personal Glory",
"Extreme Individualism",
"Repay Debt",
"Innovation Over Stability",
"Meritocracy",
"Secrecy",
"Adventuring",
"Awaiting Divine Re-visit",
"Reputation Over Reality",
"Cosmic Balance Above Morality",
"Astrology",
"Strict Clearance / Permission",
"Procreation",
"Strong Protect the Weak",
"Beauty",
"Utility Above Aesthetics",
"Unity Through Conquest",
"Freedom Through Chaos",
"Bloodlines Matter Most",
"Suffering is Enlightenment",
"Fear as Governance",
"Sacred Geometry",
"Isolation",
"Self-Sufficiency",
"Natural Order",
"Cyclic Reincarnation",
"Silence",
"Tributes to Dead",
"Guide Wanderers",
"Wandering",
"Dreams as Prophecy",
"Strength in Numbers",
"Eternal Youth",
"Shared Dreams",
"Forbidden Love",
"Ritual Above Reason",
"Shadows Over Light",
"Hunger for Knowledge",
"Eternal Conflict",
"Unshakable Loyalty",
"Endless Celebration",
"Wood & Steel Replace Flesh",
"Emotions as Currency",
"Fire as Purifier",
"Songs of Power",
"Truth in Madness",
"Time as Illusion",
"Eyes Always Watching",
"Pain as Pleasure",
"Crystals",
"Wetness",
"Masks",
"Patriarchy",
"Matriarchy",
"Hospitality",
"Rebellion",
"Stoicism",
"Foresight",
"Lunar Cycles",
"Symbiosis with Nature",
"Nocturnal",
"Altruism",
"Introspection",
"Decadence",
"Mysticism",
"Tinkering",
"Blood Sacrifice",
"Mind Over Matter",
"Minimalism",
"Philosophy",
"Nomadism",
"Theater",
"Visual Art",
"Song and Dance",
"Mimicry",
"Dirt",
"Chakras",
"Oaths",
"Imagination",
"Curiosity",
"Virtue",
"Magic",
"Purity",
"Filth",
"Speed",
"Strength",
"Gardening",
"Chivalry",
"Storytelling",
"Duels",
"Games",
"Fasting",
"Divination",
"Herbalism",
"Building ",
"Relics",
"Hoarding",
"Pilgrimage",
"Prophecy",
"Control of Fire",
"Mastery of Water",
"Command of Earth",
"Harnessing the Wind",
"Control of Plants",
"Demonology",
"Necromancy",
"Illusion",
"Alchemy",
"Secret Societies",
"Symbolism",
"Theft OK",
"Murder OK",
"Chastity",
"Tattooing",
"Body Modification",
"Puppetry",
"Cannibalism",
"Drugs OK",
"Trance States",
"Fear of the Unknown",
"Worship of the Sun",
"Worship of the Moon",
"Worship of Nature",
"Worship of the Stars",
"Worship of Nature Spirits",
"Worship of Ancestral Spirits",
"Worship of Abstract Concepts",
"Worship of Deified Heroes",
"Worship of Alien Beings",
"Fear of the Forest",
"Fear of the Sea",
"Fear of the Mountains",
"Fear of the Desert",
"Fear of the Sky",
"Fear of the Underground",
"Fear of the Night",
"Fear of the Day",
"Fear of Silence",
"Fear of Noise",
"Fear of Touch",
"Fear of Sight",
"Fear of Smell",
"Fear of Taste",
"Fear of Emotion",
"Exploration",
"Learning",
"Reading",
"Teaching",
"Debate",
"Meditation",
"Prayer",
"Destiny",
"Cosmic Balance",
"Cleanliness",
"Fomo",
"Greed",
"Envy",
"Wrath",
"Sloth",
"Pride",
"Lust",
"Ghosts & Spirits",
"Good",
"Evil",
"Ignorance",
"Ugliness",
"Courage",
"Cowardice",
"Love",
"Hate",
"Sorrow",
"Joy",
"Hope",
"Doubt"
]