export default [
  "Wheat",
  "Barley",
  "Rye",
  "Vegetables",
  "Fruit orchards",
  "Fishing",
  "Beekeeping",
  "Dairy",
  "Poultry",
  "Pigs",
  "Cattle",
  "Sheep",
  "Goats",
  "Herbs",
  "Grapes",
  "Cobbling",
  "Weaving",
  "Tailoring",
  "Dyes",
  "Spinning",
  "Knitting",
  "Embroidery",
  "Tanning",
  "Blacksmithing",
  "Armoring",
  "Metalworking",
  "Woodworking",
  "Carpentry",
  "Masonry",
  "Bricks",
  "Pottery",
  "Glass blowing",
  "Basket weaving",
  "Candles",
  "Soap",
  "Rope",
  "Saddles",
  "Bells",
  "Bookbinding",
  "Baking",
  "Brewing",
  "Distilling",
  "Wine",
  "Milling",
  "Butchery",
  "Salt",
  "Oil pressing",
  "Pickling",
  "Cheese",
  "Smoking",
  "Cartwrighting",
  "Shipbuilding",
  "Wheelwrighting",
  "Port services",
  "Caravanning",
  "Market trading",
  "Scribing",
  "Teaching",
  "Medicine",
  "Midwifery",
  "Lawkeeping",
  "Innkeeping",
  "Tavern keeping",
  "Entertainment",
  "Cartography",
  "Astrology",
  "Alchemy",
  "Wool",
  "Linen",
  "Cotton",
  "Feathers",
  "Parchment",
  "Paper",
  "Trapping",
  "Hunting",
  "Forestry",
  "Charcoal",
  "Mining",
  "Quarrying",
  "Peat cutting",
  "Jewelry",
  "Goldsmithing",
  "Silversmithing",
  "Ivory carving",
  "Enameling",
  "Stained glass",
  "Illuminated manuscripts",
  "Falconry services",
  "Horse breeding",
  "Dog breeding",
  "Shepherding",
  "Leatherworking",
  "Water mill operation",
  "Windmill operation",
  "Bridge building",
  "Road maintenance",
  "Sanitation",
  "Watchkeeping",
  "Toys",
  "Chandlering",
  "Onions",
  "Garlic",
  "Turnips",
  "Flax",
  "Hemp",
  "Nuts",
  "Berries",
  "Mushrooms",
  "Salted fish",
  "Herbal teas",
  "Spices",
  "Clams",
  "Oysters",
  "Eels",
  "Ale brewing",
  "Mead brewing",
  "Vinegar",
  "Apple cider",
  "Pear cider",
  "Pickled eggs",
  "Geese",
  "Ducks",
  "Rabbits",
  "Pigeons",
  "Wicker furniture",
  "Thatches",
  "Clay digging",
  "Plaster",
  "Lime burning",
  "Chalk gathering",
  "Terracotta production",
  "Torches",
  "Shingles",
  "Roof tiling",
  "Gutters",
  "Fencing",
  "Gates",
  "Doors",
  "Window crafting",
  "Signs",
  "Banners",
  "Tapestry weaving",
  "Rug weaving",
  "Nets",
  "Fishing tackles",
  "Arrows",
  "Bows",
  "Spears",
  "Swordsmithing",
  "Shields",
  "Crossbows",
  "Barrels",
  "Casks",
  "Tubs",
  "Buckets",
  "Wheelbarrows",
  "Plows",
  "Scythes",
  "Hoes",
  "Rakes",
  "Spades",
  "Grindstone crafting",
  "Anvils",
  "Forge building",
  "Kiln building",
  "Cauldrons",
  "Cooking pots",
  "Pans",
  "Knife sharpening",
  "Harnesses",
  "Bridles",
  "Stirrups",
  "Spurs",
  "Belts",
  "Pouches",
  "Boots",
  "Gloves",
  "Hats",
  "Cloaks",
  "Curtains",
  "Wagon painting",
  "Wall painting",
  "Sign painting",
  "Book illuminating",
  "Quills",
  "Ink",
  "Scrolls",
  "Chalkboards",
  "Tablet carving",
  "Statue carving",
  "Relic crafting",
  "Caskets",
  "Chalices",
  "Altar crafting",
  "Cemetery keeping",
  "Grave digging",
  "Church bell ringing",
  "Parchment cutting",
  "Hay",
  "Barley malt",
  "Oatmeal",
  "Millet",
  "Chestnuts",
  "Hazelnuts",
  "Walnuts",
  "Plums",
  "Figs",
  "Dates",
  "Cabbages",
  "Carrots",
  "Parsnips",
  "Beets",
  "Cherries",
  "Apricots",
  "Melons",
  "Quince",
  "Gooseberries",
  "Elderberries",
  "Hops",
  "Herbal salves",
  "Poultices",
  "Tonics",
  "Meat curing",
  "Grain storage",
  "Granary maintenance",
  "Tents",
  "Mirrors",
  "Glass",
  "Threshing",
  "Winnowing",
  "Plow operation",
  "Field irrigation",
  "Orchard pruning",
  "Vineyard tending",
  "Shearing",
  "Wool carding",
  "Spindles",
  "Loom construction",
  "Drapery",
  "Tunics",
  "Stocking knitting",
  "Chainmail crafting",
  "Helmet forging",
  "Armor polishing",
  "Quivers",
  "Black powder preparation",
  "Lanterns",
  "Window leadwork",
  "Stained glass assembly",
  "Tile glazing",
  "Fresco painting",
  "Mural designing",
  "Cistern building",
  "Aqueduct maintenance",
  "Well digging",
  "Wine barrels",
  "Oil lamps",
  "Soapstone carving",
  "Chalk cutting",
  "Sealing wax production",
  "Scroll cases",
  "Writing desk crafting",
  "Chairs",
  "Benches",
  "Stools",
  "Tables",
  "Chests",
  "Bed frames",
  "Mattress stuffing",
  "Cloth mending",
  "Laundry services",
  "Daggers",
  "Halberds",
  "Pikes",
  "Chains",
  "Locksmithing",
  "Key forging",
  "Traps",
  "Cages",
  "Birds",
  "Hawk training",
  "Sheepdog training",
  "Horse grooming",
  "Stable keeping",
  "Feed",
  "Muck spreading",
  "Compost",
  "Herb drying",
  "Flowers",
  "Garland weaving",
  "Perfume",
  "Incense",
  "Censer crafting",
  "Rosary crafting",
  "Pilgrim badges",
  "Coin minting",
  "Tax collecting",
  "Court heralding",
  "Letter delivery",
  "Message running",
  "Storytelling",
  "Poetry recitation",
  "Musical instruments",
  "Drums",
  "Nettle weaving",
  "Rushlights",
  "Horn carving",
  "Bone needle crafting",
  "Antler tool",
  "Pig bristle collection",
  "Feather quill sharpening",
  "Fish glue",
  "Tree resin gathering",
  "Amber polishing",
  "Jet carving",
  "Turf cutting",
  "Bee skep",
  "Hedge laying",
  "Dry stone wall building",
  "Moat digging",
  "Palisade construction",
  "Dovecote building",
  "Wattle and daub crafting",
  "Flint knapping",
  "Obsidian tool crafting",
  "Charred wood drawing",
  "Peat stacking",
  "Ash lye production",
  "Dung collection",
  "Manure spreading",
  "Heraldry painting",
  "Tourney armor repair",
  "Joust lance crafting",
  "Knight training",
  "Squire instruction",
  "Warhorse training",
  "Siege engine building",
  "Catapult crafting",
  "Ballista construction",
  "Trebuchet assembly",
  "Battering rams",
  "Drawbridge maintenance",
  "Portcullis repair",
  "Dungeon keeping",
  "Torchbearer services",
  "Watchtower guarding",
  "Firewood bundling",
  "Snow clearing",
  "Ice cutting",
  "Cold storage maintenance",
  "Salt pan digging",
  "Whale oil refining",
  "Lantern oil",
  "Hemp rope splicing",
  "Candle wick braiding",
  "Soap ash production",
  "Textile printing",
  "Herbal sachets",
  "Moth repellent crafting",
  "Wool felt production",
  "Sheepskin tanning",
  "Rabbit fur processing",
  "Otter trapping",
  "Beaver pelt preparation",
  "Swan feather gathering",
  "Eel trap weaving",
  "Crayfish",
  "Leeches",
  "Snails",
  "Frogs",
  "Bat guano collection",
  "Owl training",
  "Rook keeping",
  "Goose plucking",
  "Swallow nest harvesting",
  "Hedgehog collecting",
  "Mole trapping",
  "Weasel taming",
  "Ferret breeding",
  "Pine marten trapping",
  "Wolf hunting",
  "Bear baiting",
  "Falcon perch crafting",
  "Arrow fletching",
  "Bowstrings",
  "Quiver strap weaving",
  "Shield boss forging",
  "Gauntlet crafting",
  "Greaves",
  "Pauldrons forging",
  "Tabard stitching",
  "Standard bearer training",
  "Siege ladders",
  "Belfry tower construction",
  "Fire beacon tending",
  "Signal flags",
  "Battle horn carving",
  "Drum skin stretching",
  "Tavern gaming",
  "Dice carving",
  "Card deck painting",
  "Public punishment crafting",
    "Mercury",
    "Cat fur",
    "Velvet",
    "Silk",
    "Damask",
    "Gold ingots",
    "Silver ingots",
    "Copper bars",
    "Tin bars",
    "Bronze tools",
    "Iron tools",
    "Steel swords",
    "Fine wool",
    "Dyed wool",
    "Linen thread",
    "Spun cotton",
    "Embossed leather",
    "Soft leather",
    "Hard leather",
    "Tanned hides",
    "Sheepskins",
    "Goat skins",
    "Deer pelts",
    "Fox pelts",
    "Sable pelts",
    "Mink pelts",
    "Beaver pelts",
    "Otter pelts",
    "Ivory",
    "Carved bone",
    "Amber beads",
    "Polished amber",
    "Jet jewelry",
    "Glass beads",
    "Blown glass vases",
    "Stained glass windows",
    "Gold jewelry",
    "Silver jewelry",
    "Gilded mirrors",
    "Wax seals",
    "Sealing wax",
    "Dyed parchment",
    "Illuminated manuscripts",
    "Fine quills",
    "Black ink",
    "Red ink",
    "Herbal perfumes",
    "Essential oils",
    "Rosewater",
    "Soap",
    "Beeswax",
    "Candles",
    "Spices",
    "Cinnamon",
    "Cloves",
    "Nutmeg",
    "Pepper",
    "Saffron",
    "Salt",
    "Olive oil",
    "Walnut oil",
    "Linseed oil",
    "Wine",
    "Mead",
    "Ale",
    "Distilled spirits",
    "Honey",
    "Cheese",
    "Cured meats",
    "Dried fish",
    "Salted fish",
    "Smoked fish",
    "Pickled vegetables",
    "Dried fruits",
    "Raisins",
    "Almonds",
    "Hazelnuts",
    "Walnuts",
    "Chestnuts",
    "Flax fibers",
    "Hemp fibers",
    "Charcoal",
    "Firewood",
    "Barrels",
    "Casks",
    "Fine pottery",
    "Porcelain",
    "Stone tiles",
    "Terracotta tiles",
    "Marble blocks",
    "Polished marble",
    "Granite blocks",
    "Slate tiles",
    "Soapstone",
    "Obsidian",
    "Coal",
    "Sulfur",
    "Saltpeter",
    "Gunpowder",
    "Boat Crafting",
];