export default [
"Monarchy (hereditary king/queen)",
"Imperial Governance (under an emperor)",
"Oligarchy (rule by a wealthy elite)",
"Republic (elected representatives)",
"Theocracy (rule by religious leaders)",
"Merchant Oligarchy (dominated by traders/guilds)",
"Viceroyalty (governed by a royal appointee)",
"Consulate (led by consuls)",
"Plutocracy (rule by the wealthy)",
"Magocracy (rule by mages or intellectual elite)",
"Senate-based Government",
"Civic Commune (collective urban council)",
"City-state Democracy",
"Mayor-Council System",
"Free Imperial City (nominally free within an empire)",
"Council of Elders",
"Bandit-Controlled",
"Chosen-One Rule",
"Rule by Lottery",
"Military Governorate",
"Lord-Mayorship",
"Triumvirate (rule by three leaders)",
"Protectorate City (under a neighboring power)",
"Dynastic Leadership (controlled by a family)",
"Feudal City (subject to a local lord)",
"Sheriff-led Administration",
"City-State Autonomy",
"Feudal Lordship",
"Garrison City (ruled by military leaders)",
"Maritime Rule (led by shipowners)",
"Minor Noble Leadership",
"Elected Magistracy",
"Monastic City (led by monks or abbots)",
"Feudal Appointee Rule",
"Local Noble Stewardship",
"Charter Town Rule",
"Militia Governance",
"Guild Representative Rule",
"Knightly Protectorate",
"Rotating Magistracy",
"Merchant Governance",
"Tithing Governance (based on local tithes)",
"Loyalist Protectorate (serves a larger entity)",
"Manor Collective",
"Dual Magistracy",
"Ward Leader Governance",
"Eldest Rule",
"Templar Stewardship",
"Bonded Guild Rule",
"Minor Fiefdom Leadership",
"Manorial Autocracy",
"Bailiff-appointed Rule",
"Rotating Elder Leadership",
"Local Guild Federation",
"Trade Hub Council",
"Knight-Protectorate",
"Scribe-led Governance",
"Agricultural Collective Leadership"
]