export default [
"Monarchy (hereditary king/queen)",
"Imperial Governance (under an emperor)",
"Oligarchy (rule by a wealthy elite)",
"Republic (elected representatives)",
"Theocracy (rule by religious leaders)",
"Stratocracy (military rule)",
"Bureaucracy (rule by officials)",
"Merchant Oligarchy (dominated by traders/guilds)",
"Viceroyalty (governed by a royal appointee)",
"Consulate (led by consuls)",
"Archiepiscopal Rule (led by an archbishop)",
"Plutocracy (rule by the wealthy)",
"Guild Republic (governed by guild leaders)",
"Magocracy (rule by mages or intellectual elite)",
"Senate-based Government",
"Civic Commune (collective urban council)",
"City-state Democracy",
"Client City (subservient to a larger kingdom)",
"Syndicalism (rule by labor unions)",
"Federal City (autonomous but part of a larger federation)",
"Mayor-Council System",
"Prince-Bishopric (bishop with secular authority)",
"City Charter Rule (chartered by a king)",
"Patrician Governance (led by aristocrats)",
"Free Imperial City (nominally free within an empire)",
"Trade Republic",
"Council of Elders",
"Bandit-Controlled",
"Chosen-One Rule",
"Rule by Lottery",
"Military Governorate",
"Ecclesiastical City (ruled by the Church)",
"Lord-Mayorship",
"Urban Commune",
"Triumvirate (rule by three leaders)",
"Protectorate City (under a neighboring power)",
"Dynastic Leadership (controlled by a family)",
"Town Assembly Governance",
"Craft Guild Authority",
"Feudal City (subject to a local lord)",
"Seafaring Confederacy",
"City Guild Sovereignty",
"Magistrate Governance",
"Sheriff-led Administration",
"Stewardship (governed by a steward)",
"Collegial Governance (ruled by elected peers)",
"Baronial City (ruled by a baron)",
"City-State Autonomy",
"Marcher City (on a border or frontier)",
"County Capital (governed by a count)",
"Feudal Lordship",
"Garrison City (ruled by military leaders)",
"Trade Hub Republic",
"Independent Council Rule",
"Maritime Rule (led by shipowners)",
"Minor Noble Leadership",
"Township Governance",
"Sovereign Commune",
"Elected Magistracy",
"Charter Town Autonomy",
"Bailiff Governance",
"Urban Serfdom",
"Monastic City (led by monks or abbots)",
"Feudal Appointee Rule",
"Town Warden System",
"Local Noble Stewardship",
"Charter Town Rule",
"Militia Governance",
"Guild Representative Rule",
"Burgomaster Leadership (mayor-like figure)",
"Ecclesiastical Stewardship",
"Knightly Protectorate",
"Lord of the Manor Rule",
"Rotating Magistracy",
"Village Eldership",
"Squire-led Administration",
"Merchant Governance",
"Tithing Governance (based on local tithes)",
"Loyalist Protectorate (serves a larger entity)",
"Abbacy Rule (abbot or abbess leadership)",
"Manor Collective",
"Dual Magistracy",
"Ward Leader Governance",
"Town Elder Rule",
"Thane Governance",
"Parish Council Leadership",
"Rural Feudalism",
"Reeve-led Authority",
"Yeoman Magistracy",
"Hereditary Burgess Rule",
"Templar Stewardship",
"Bonded Guild Rule",
"Minor Fiefdom Leadership",
"Manorial Autocracy",
"Bailiff-appointed Rule",
"Rotating Elder Leadership",
"Local Guild Federation",
"Rural Trade Hub Council",
"Knight-Protectorate",
"Tenant Lordship (appointed tenant oversees governance)",
"Ecclesiastical Protection",
"Scribe-led Governance",
"Agricultural Collective Leadership"
]