export default [ "Butterfly Cover - Moving through marked areas triggers butterflies, providing quarter cover for one round and imposing an attack penalty.",
"Hidden Stream - Grass-covered stream, roll to cross unnoticed (or fall in). Inside, creatures have half cover but disadvantage on attacks",
"Dandelions - Walking through dandelions forces a roll or else sneezing fits, costing the creature their bonus action.",
"Wild Horses - On a set round, wild horses charge through. A roll notices early; players must move or be trampled",
"Vultures - Unconscious characters may be attacked by impatient vultures circling above.",
"Crows - Disturbing crows triggers their retaliation. They swarm offenders and remember enemies.",
"Storm - Creatures roll a d6; on a 1, they make a Dex save or take lightning damage. Metal wearers automatically fail.",
"Raging Winds - Gale-force winds blow creatures 5 feet randomly unless a Strength save is made.",
"Sleeping Flowers - Crossing flowers triggers a Constitution save or causes sleep, requiring damage or an ally’s action to awaken.",
"Ancient Ruins - Players may use ruins for cover or high ground, but their preservation may hold future significance.",
"Dry Grass - Dry grass risks wildfire from fire, lightning, or reflective metal gear.",
"Heavy Undergrowth - Thick vegetation causes difficult terrain, with latchweeds slowing movement further.",
"Ant Hills - Stepping on hidden ant hills summons an angry swarm unless spotted with Perception 12",
"Beehive - Shooting or hitting a hive releases bees that attack nearby creatures.",
"Prairie Dog Holes - Shallow holes make terrain difficult. Large creatures risk collapsing tunnels, halting movement.",
"Dung Piles - Slippery, require a Con save to avoid losing actions or reactions. Falling prone in them can trigger vomiting (CON save).",
"Tall Grass - Grass obscures vision, applying underwater combat rules without negating penalties via swimming speed.",
"Rabbit Warrens - Moving faster than half-speed risks a Dexterity save to avoid falling prone in burrows.",
"Tornado - A tornado approaches, altering conditions each round until it hits, pulling creatures in and heavily obscuring the battlefield.",
"Snake in Grass - Passive Perception ato notice the venomous snake. Entering its square provokes an attack and poison save.",
"Sinkhole - Proximity triggers a sinkhole that halves movement and traps creatures with nearby foes.",
"Frightened Enemies - Enemies appear scared, only for a larger predator to replace them in the initiative order.",
"Pollen Poison - Pollen inflicts the poisoned condition or vision loss unless a saving throw is passed.",
"Deafening Wind - Powerful gusts deafen and prevent communication.",
"Defending Nest - Monster aggression ceases if players retreat from its nest.",
"Stone Circle - A stone circle repels monsters but may awaken a spirit if used for refuge.",
"Crop Circle - A crop circle deters monsters but risks alien force intervention.",
"Tortoise Herd - Tortoises rise beneath combatants, moving 10 feet per turn and altering battlefield positions.",
"Bone Warnings - Scattered animal bones suggest a coming threat.",
"Hailstorm - Falling hail deals bludgeoning damage unless players find cover.",
"Prairie Fire - Combat ends in X rounds as fire sweeps the field.",
"Sinkhole Water - Ancient sinkhole water allows super jumps but has limited uses.",
"Sentient Grass - Grass restrains prone creatures (Strength save) and creates difficult terrain.",
"Sharp Grass - Fast movement risks 1d4 slashing damage unless armored.",
"Ash Field - Ash clouds blind players every 1d4 rounds as wind stirs it up.",
"Woven Grass Barriers - Hidden barriers block movement unless spotted.",
"Exposed Tower - Enemies hold high ground while grassland offers no cover.",
"Spider Webs - Webbing creates difficult terrain and risks venomous spiders imposing the poisoned condition.",
"Tall Grass Concealment - Tall grass grants partial concealment, stealth bonuses, and difficult terrain.",
"Devilsburr - Contact with Devilsburr causes escalating poison damage unless removed with Medicine roll or magic.",
"Earthquake - Shaking ground knocks creatures prone (Dexterity save) and creates crevasses.",
"Gravity Surge - Gravity spikes or lightens, altering movement and attacks for X rounds.",
"Frost Mushrooms - Damaging frost mushrooms creates slippery ice or freezes creatures briefly.",
"Paralysis Mushrooms - Damaging yellow mushrooms emits spores that paralyze creatures for a round.",
"Hallucination Mushrooms - Stepping on rainbow mushrooms risks hallucinations and random attacks.",
"Necrotic Mold - Contact with mold deals increasing necrotic damage until removed by restoration or surgery.",
"Abandoned Shack: Possible supplies or weapons. Risk of collapse.",
"Unexpected Reinforcements",
"Campsite: Tents, bonfire",
"Flock of Birds: Startled, causes distraction/damage.",
"Hidden Cache: Weapons, food, or valuables. Requires search.",
"Unstable High Ground: A cliff or balcony, but may collapse if attacked or too much weight",
"Non-Combatants: Panicked crowds, innocent animals/civilians, etc",
"Old Battlefield: Possible artifacts/weapons. May trigger undead.",
"Rubble: Difficult terrain.",
"Beartrap: May be set or rusted.",
"Sudden Rainfall: All dirt is now mud, everyone has resistance to fire, ranged weapons lose some range. ",
"Animal Holes: Hidden. Tripping hazard. May be occupied.",
"Guard Dog: Hostile within leash range. May be untied.",
"Hay Bales: Cover. Highly flammable.",
"Barbed Wire: Difficult terrain & damage",
"Circling Vultures: Attack unconscious or weak targets.",
"Moonshine Still: Risk of explosion.",
"Rotten Tree: May fall randomly.",
"Snake in Grass: Bite and flee.",
"Wood Shed: May contain critters or useful items.",
"Steep Hillside: Risk of sliding down.",
"Hot Springs: Healing or scalding pools.",
"Large Herbivores: Spooked, may stampede.",
"Rope Bridge: Poor condition. Cross with care.",
"Large Egg: About to hatch",
"Marsh Gas: Bubbling, occasionally on fire.",
"Frost Pockets: Sudden and slippery depressions.",
"Bat Cave: Thousands of bats fly out",
"Tower Ruins",
"Water mill wheel",
"Abandoned Weather-worn trenches",
"Abandoned Siege Weapons",
"Abandoned Farm House",
"Irrigation Ditch",
"Cacti",
"Wagon with broken wheel: Fix or search",
"Cauldron: Contains random ingredients, potentially a useful brew.",
"Corpse: May contain useful items",
"Dangerous animal in cage",
"Statue: May be toppled or climbed",
"Log: Sharp branches poking out",
"Mud: Difficult terrain. If pushed on, DEX save or fall. ",
"Pottery: May contain something useful ",
"Rug: May be pulled out from under an opponent causing them to trip",
"Vines: Swing, climb, use as rope. ",
"Winch: Operate (draw bridge, portcullis, lift, well)",
"Within a laboratory, stray hits can break experiments with unusual results ",
"The ground is floolike quicksand, causing people to start sinking if they stand still or have too much weight",
"The ground is icy, move at half speed or risk falling",
"An automated magical construction sight turns on",
"Tar pits",
"Snake pits",
"Steep hill in a rain storm with mudslides",
"Thick fog rolls in, can't see far",
"Wind Tunnel: Strong gusts push or pull combatants.",
"Glowing Mushrooms: Provide light but are highly toxic.",
"Thunderstorm: Lightning strikes randomly.",
"Abandoned Graveyard: Graves may release undead.",
"Meteor Shower: Small impacts deal area damage.",
"Shifting Sands: Rearranges terrain every turn.",
"Quicksand Patch: Sinks combatants slowly unless aided.",
"Crumbled Wall: Could collapse on someone",
"Frozen Pond: Slippery; heavy blows may crack the ice.",
"Volcanic Cracks: Periodically spew molten lava.",
"Geysers: Erupt periodically, scalding anyone nearby.",
"Barrels of Explosive Oil",
"Hanging Lanterns that spilled oil on the floor",
"Magic Mirrors",
"Reinforcements horn/gong",
"Trap Door",
"Cursed Blood: Explodes when killed.",
"Elementalist: Moves around field to use spells based on what it's touching (water, tree, etc)",
"Split Form: Divides into smaller foes when struck.",
"Blinding Burst: Emits light after taking damage.",
"Unstable Construct: Self-destructs when cornered.",
"Falling Rocks: From ceilings or cliffs.",
"Rising Water: Slowly floods the area.",
"Cracked Ground: Risk of fissures opening mid-combat.",
"Tornado: Moves unpredictably, tossing combatants.",
"Encroaching fire",
"Strong Magic Field: Spells cause random magic",
"Shifting Gravity: Pulls combatants in odd directions.",
"Arcane Runes: Power up whoever stands on them.",
"Slow Rolling Boulder: Moves each turn, crushing all in its path.",
"Acid Pool: Gradually spreads outward.",
"Magnetized Boulders: Pulls metal weapons and armor near them",
"Falling Stalactites: Drop randomly; piercing damage.",
"Twisting Roots: Entangle combatants who remain still for too long.",
"Tidal Wave: Sweeps across the battlefield, knocking creatures prone and dragging them",
"Dust Storm: Comes and goes, imposing disadvantage on ranged attacks and obstructing vision",
"Shifting Terrain: Rearranges when struck",
"Razorgrass: Damages creatures moving through it.",
"Exploding Crystals: Trigger chain reactions when struck.",
"Enchanted Bell: Rings to stun or charm nearby creatures.",
"Suspended Net: Can be dropped to entangle enemies.",
"Flamethrower Trap: Activated by switches or pressure plates.",
"Slingshot Mechanism: Launches creatures across the battlefield.",
"Various child-proof potions scattered around, takes 1 turn to figure out how to unlock each one. ",
"Teleport Pads: Link two points",
"Pulley System: Moves heavy objects",
"Runed Obelisk: Attacks nearby creatures",
"Cursed Idol: Deals psychic damage when approached",
"Enchanted Throne: Grants buffs but locks the user in place.",
"Fallen Banner: Inspires allies who raise it.",
"Chiming Crystal: Emits sound waves; disrupts concentration.",
"Oil Slick: Burnable and slippery.",
"Phase Shifter: Teleports after damage.",
"Molting Beast: Sheds skin, reducing AC but increasing speed.",
"Mindlinked Minions: Share damage or buffs",
"Possessing Spirit: Jumps between players and NPCs.",
"Adaptive Predator: Gains resistance to the last damage type it suffered.",
"Regenerating Limb: Grows a weaponized appendage after being dismembered.",
"Gravity Wells: Small areas of inverted gravity; creatures float upward.",
"Slime Coated Floor: Sticky, moves around on its own",
"Crystalline Cavern: Reflects light and sound, creating disorienting effects.",
"Magnetic Spires: Pull or repel metallic objects and creatures wearing armor.",
"Rock slides",
"Void Rifts: Blink creatures out of combat momentarily if touched and fail save",
"Mushroom Forest: Fungi release spore clouds when damaged",
"Living Vines: Grapple and attack creatures.",
"Field of Bones: Difficult terrain with a chance of skeletal hands emerging.",
"Frozen Fog: Freezes creatures who remain within for too long.",
"Fog of Desire: Illusions distract and confuse",
"Corrupted Water: Deals necrotic damage when waded through.",
"Giant Clockwork Gears: Constantly rotating platforms.",
"Thin Ice: Collapses under too much weight.",
"Magical Fog: Randomly teleports creatures within its boundaries.",
"Blighted Ground: Poisonous and damages those standing on it.",
"Roaring Waterfall: Deafens and silences all within its area.",
"Cursed Shadows: Attack creatures who step into them.",
"Crystal Spikes",
"Creeping Ice: Spreads slowly, freezing terrain and creatures.",
"Moving Sand: Acts like a treadmill, pulling creatures backward.",
"Haunted Fog: Whispers distract and frighten creatures.",
"Molten Veins: Glowing cracks periodically erupt with flame.",
"Abyssal Scree: Rocks scream when stepped on",
"Luminous Pools: Glow brightly, maybe toxic",
"Echoing Canyon: Amplifies noise, disrupting spells and stealth.",
"Ash Storm: Burns and blinds creatures caught within.",
"Frozen Bubbles: Pop under pressure, releasing freezing air.",
"Living Trees: Attack creatures when disturbed.",
"Petrified Tentacles: Sharp and brittle, may snap and fall.",
"Rippled Glass Field: Distorts vision and sound.",
"Shimmering Mirage: Disorients, creating illusory terrain features.",
"Runed Circles: Provide buffs or debuffs to anyone stepping inside.",
"Ropes/vines, multi-stories, and catapults",
"Deadly Pendulums: Swing in predictable arcs; lethal if timed poorly.",
"Totem of Warding: Protects creatures within range until destroyed.",
"Falling Logs: Roll across the battlefield, crushing creatures.",
"Telekinetic Crystals: Allow creatures to move objects or enemies when crushed",
"Shallow Lava: Safe to step briefly; prolonged contact burns.",
"Rotating Bridges: Change direction each round.",
"Blood River: Slowly sucks blood",
"Glass Floor: Shatters under heavy impacts.",
"Gravitational Pillars: Push or pull nearby creatures.",
"Shapeshifting Trees: Transform to mimic nearby creatures or hazards",
"Screaming Wind",
"Living Moss: Grows rapidly, encasing creatures if they stand on it too long",
"Arcane Currents: Move spells cast within.",
"Fanged Rocks: Bite creatures who climb them.",
"Crumbling Steps: Lose stability each use.",
"Arcane Levers: Activate traps or terrain shifts.",
"Sealed Sarcophagus: Risk-reward for opening mid-combat.",
"Spinning Runes: Randomly buff or debuff when touched.",
"Magic Fountains: Random healing or harm when drunk.",
"Binding Vines: Traps anyone entering.",
"Trapping Cages: Trigger manually for area control.",
"Falling Cages: Trigger via pressure plate",
"Lever branch: Raises or drops different sections of the floor.",
"Fire-Breathing Statue: Triggered by switches.",
"Armor to Weapon: Loses AC but gains damage output.",
"Blood Frenzy: Attacks faster when below half HP.",
"Surge Weapon: AoE damage on critical hits.",
"Spiked Boots: Damaging wearer creates damaging terrain nearby.",
"Mirror Armor: Creates illusions after being hit.",
"Warding Hat: Damages casters nearby when targeted.",
"Trenchcoat: Releases small creatures when damaged.",
"Electrified Floor: Deals lightning damage when touched.",
"Glowing Vines: Illuminate dark areas, but attract creatures.",
"Cave Mushrooms: Explode into spores when disturbed.",
"Whirlpool: Pulls creatures toward its center.",
"Staggering Wind: Forces creatures to make balance checks.",
"Pit of Thorns",
"Hailstorm Zone: Deals cold damage at the start of each round.",
"Rockslide Path: Triggered by loud sounds or weight.",
"Glimmering Creek: Heals those who drink from it.",
"Lava Flow: Spreads each turn.",
"Toxic Swamp: Deals poison damage over time.",
"Blood Altar: Powers those who spill blood near it.",
"Iron Chains and shackles attached to wall",
"Geyser: Erupts after a certain number of rounds.",
"Sacrificial Circle: Amplifies magic but harms those standing in it.",
"Stone Summoning Circle: If any stones are disturbed, summons a massive creature sealed within",
"Arcane Compass: Points to the most valuable item in the area.",
"Lunar Pool: Grants temporary invisibility or visibility.",
"Alchemy Table: Create random potions under pressure.",
"Vengeful Spirit: Summons a ghost after dying",
"Crimson Veil: Becomes invisible after they hit, visible when struck",
"Consuming Form: Sucks in anyone within 5 feet when reduced to 0 HP. Sealed half within the body, unable to move lower half. Can escape by destroying corpse. ",
"Ethereal Shift: Becomes incorporeal for 1 round after taking damage.",
"Lifeforce Absorption: Drains HP from nearby creatures, adding it to their own",
"Summon Allies: Calls reinforcements after reaching half health.",
"Fall Back: Everyone falls back to more advantagous terrain after X turns. ",
"Carnivorous Plants: Attack creatures that come too close.",
"Illusory Walls: Walls that appear solid but can be passed through.",
"Webs: Sticky and flammable.",
"Berserk Beast: Gains strength each turn.",
"Timed Explosives: Detonate after a set number of turns.",
"Shadow Creatures: Emerge from darkness, attacking stealthily.",
"Reflective Pool: Can transport creatures to a mirrored plane.",
"Shifting Illusions: Terrain changes appearance each round.",
"Magic Circles: Enhance or weaken magic within.",
"Enchanted Chains/Vines: Bind and restrain on contact.",
"Mimics",
"Arcane Storm: Random spell effects each round.",
"Temporal Rift: Causes time anomalies in the area.",
"Screeching Frogs: Emit a deafening noise when disturbed.",
"Puppet Strings: Control and manipulate enemy movements.",
"Sentient Weapons: Attack on their own if not held.",
"Mirror Trap: Creates duplicate illusions of combatants.",
"Blessed Ground: Heals creatures standing on it.",
"Whispering Oaks: Whisper secrets or commands to those near.",
"Sacrificial Altar: Provides powerful buffs at a cost.",
"Charmed Beasts: Attack whoever disturbs their rest.",
"Polymorph Pit: Temporarily transforms creatures.",
"Enchanted Tapestry: Traps creatures in a magical landscape.",
"Enchanted Paintings: Can travel into and out of to retrieve items, etc held within. Might contain enemies, loot, etc",
"Raging River: Sweeps creatures away.",
"Stone Guardians: Activate to protect the area.",
"Arcane Beacon: Attracts hostile creatures.",
"Living Statues: Animate to defend themselves.",
"Enchanting Melody: Charms those who hear it.",
"Frozen Fountain: Freezes creatures who touch it.",
"Haunting Spirits: Distract and disorient",
"Crushing Walls",
"Arcane Spikes: Burst from the ground when magic is used.",
"Phantom Swords: Hover and attack at will.",
"Hypnotic Pattern: Mesmerizes those who look at it.",
"An old woman",
"A group of children",
"A pile of logs propped up by a pair of planks",
"A sawmill blade",
"A bucket of glass shards",
"A glassblower's furnace with molten glass on pipes",
"A forge with hot coals and bright red swords",
"Several bottles of spirits",
"The ground gives way dropping everyone into a beholders lair forcing you to assist your opponents or face the beholder ",
"a portion of the floor falls, revealing a basement with more enemies ",
"A third force attacks both sides ",
"the room begins to fill with sand/water/etc and is shrinking on a timer",
"Non-combatants important to one side must be protected",
"The head enemy can consume its minions to regain health or fuel a special action.",
"A neutral bodak, basilisk, etc. wanders into the battle and provides a moving zone of danger",
"The guards arrive and can be convinced to join either side or attack both.",
"Wild animals that can be convinced to attack one side or the other",
"Experimental constructs emerge, which can be deconstructed",
"Steam engine/forge that makes occasional jets of scalding smoke/steam",
"Fireworks scattered about ",
"A field of flowers that emit poison when loud noises are made",
"Mushrooms that emit calming/sleepy spores when disturbed",
"Flowers that emit rage-inducing pollin when disturbed",
"Mushrooms that emit hallucination-inducing spores when disturbed",
"Mushrooms that emit fear-inducing spores when disturbed",
"Flowers that emit a confusion-inducing pollin when disturbed",
"A rock giant hurls rocks and animals from a cliff about 100ft above the party. ",
"An enemy ties oil and powder to themselves and then sets themselves on fire",
"Bees have made a hive in the chest of an animated skeleton.",
"Too much sound causes avalanche",
"The party sees the enemies from far away, but the enemies dont see the party",
"The enemies see the party coming from far away, and set up an ambush",
"The enemies have a powerful, fragile item in their posession but dont know it",
"The enemies are fighting amongst themselves",
"An earthquake begins causing fissures to appear in the ground. Dexterity save to not fall in.",
"A shadow beast attacks whoever doesnt have a light",
"The fight takes place on a bridge over a river filled with crocodiles",
"The opposition flees but comes back with a dangerous weapon",
"A animal (for example a moose) comes rushing into the fight crashing into one of the players",
"The fight takes place on a giant ant hill",
"One of the monsters plays dead, but attacks when someone comes near",
"there are smaller monsters in the walls ",
"Battle happens in a large pit. There are levers in the walls that the enemies are trying to activate. Activating the levers starts to fill the pit with water, and the more levers flipped the more water there is",
"Unstable ground and strong winds makes all misses critical misses",
"A powerful monster or opponent shows up, that is hostile to both you and your opponent",
"Buttons/levers that activate traps/etc",
"Fighting in an underwater/underground structure. Any missed shot or area of effect attack can potentially damage the walls",
"Fighting on a balance platform. Movement alters the distribution of weight causing the platform to tilt towards the heavy side.",
"Fighting on a narrow ledge",
"Fighting on a slippery slope (difficult terrain to go up, difficult terrain + chance of slipping to go down)",
"Opponents are innocent, just mind-controlled",
"You don't have to kill your opponents you only have to delay them for X turns",
"The players must kill enemies in a specific order",
"The players must race the enemy to a fixed location",
"The players must impress an audience.",
"The characters must remove exactly the right number of HP. If they do more damage than that, it heals instead of dropping below 0",
"Battle takes place on a grate-like platform. Dropped weapons and items have a chance to fall through the grate",
"A powerful ally is in a dying state. Getting that ally up and fighting is potentially more effective than fighting directly",
"Battle takes place in an area filled with hanging chains/vines. Two hands needed to move, one hand is the most available for combat.",
"Both sides must be quite for fear of waking something far more dangerous than either of them. ",
"The map has many tiny tunnels which pcs must squeeze through, but the small enemies have an easy time and can harass as they please",
"A magical storm begins, causing spells to be unpredictable or malfunction.",
"A large creature watches from a distance, only intervening if the fight gets too out of hand.",
"All speech in the area is heard as a riddle",
"Time manipulation occurs, slowing or speeding up the flow of time randomly",
"A wild magic zone causes random magical effects every few rounds, altering the environment or combatants.",
"The players are chained to each other in pairs of 2",
"A cursed weapon or item is present, offering great power but slowly taking control of the wielder's mind.",
"The combatants are forced into a ritualistic fight, where actions must be performed in specific sequences to gain an advantage.",
"The combatants are in a rapidly decaying structure, where portions of the battlefield collapse or catch fire every few rounds.",
"A powerful artifact or object can be used to turn the tide of the battle, but it requires a difficult puzzle or ritual to activate.",
"The enemies have a powerful ally watching the fight from the distance, and they can influence the battle in subtle ways (like sending healing or buffs).",
"Intense sunlight or blinding flashes makes it difficult to see or attack accurately",
"A magical effect causes all healing to be reversed, meaning any healing spells or potions hurt instead of helping.",
"The environment is filled with illusions, making it hard to distinguish between real enemies and fake ones",
"The enemies grow stronger as the battle progresses.",
"A powerful artifact in the area boosts the enemies' power but is unstable.",
"A nearby magical source is restoring the enemies’ health over time.",
"The ground is covered in explosive traps that can detonate on impact.",
"A powerful creature watches but does not intervene unless provoked.",
"The players' weapons are slowly drained of magic or effectiveness.",
"The enemies use guerrilla tactics, hiding and ambushing from shadows.",
"The players’ magic is amplified but uncontrollable, causing wild effects.",
"The combatants are affected by a powerful aura that distorts emotions.",
"A powerful NPC on the sidelines can be convinced to help",
"The combatants are fighting near a volatile magical source that could explode.",
"A massive creature is nearby but is only a threat if the fight gets too loud.",
"The enemy has a magical artifact that makes them immune to most damage unless destroyed.",
"The enemies are extremely powerful but have hidden weaknesses",
"A nearby enemy is a master of deception, constantly changing appearance.",
"The battlefield has reflective surfaces that distort the players’ perceptions.",
"The combatants must act fast to disable a dangerous magical trap in the area.",
"The players gain a temporary boon or curse based on past decisions.",
"The players must decide whether to fight or escape before reinforcements arrive.",
"A powerful enemy can only be harmed by specific weapons or methods.",
"Enemies follow a strict code of honor, limiting certain attack methods.",
"Healing magic is blocked in the area, requiring alternative methods.",
"An NPC provides limited magical help but collapses after one use.",
"Combat takes place inside a giant clock, affecting the flow of time.",
"Weapons gain unpredictable magical effects, like extra fire damage.",
"An enchanted fountain boosts players but drains life over time.",
"A dangerous creature lurks nearby, reacting to violence.",
"A powerful item grants an advantage but is unstable and risky to control.",
"A large crowd watches, and dishonorable actions affect reputation.",
"A chained creature could break free and wreak havoc if not controlled.",
"Weapons and armor are corrupted, weakening over time.",
"Magical barriers block sections of the battlefield, deactivating under certain conditions.",
"Players must protect a sacred object during combat.",
"An invisible leader controls enemies from afar, needing to be revealed.",
"Ancient weapons scattered around the battlefield come with curses.",
"Magical mirrors reflect spells, causing chaos and misdirection.",
"Environmental hazards, like a sandstorm, reduce visibility.",
"Enemies wield cursed weapons that weaken the user over time.",
"A giant creature is trapped beneath the battlefield and may emerge.",
"Players fight under a tranquilizing effect, reducing effectiveness.",
"Magical resources in the environment turn hostile when exploited.",
"A creature grows stronger if players become too emotional.",
"Historical significance triggers ancient magical defenses, aiding or hindering.",
"An enemy pleas for their life",
"An enemy tries to offer you a warm baked chocolate chip cookie in exchange for not fighting them ",
"A siren flies by, and casts charm person on a random party member or adversary ",
"One of the adversaries offers to settle things with a duel with a random party member ",
"A cute bunny appears in the middle of the battlefield ",
"A dragon much too powerful for either side to fight swoops overhead, prompting both forces to attempt to go unnoticed ",
"A pack of animals circles the field waiting to pick off the weakened victors or anyone that tries to flee ",
"A enemy stabs his ally in the back and attempts to flee with his loot ",
"The strongest enemy enters their \"final form\" doubling their stats and current hp ",
"A concealed sharpshooter begins sniping at the players with sneak attacks ",
"2d10 villagers join the fight, on whichever side the DM deems most benefits them ",
"Goblins sneak through the battlefield looting corpses and pickpocketing occupied combatants. They will avoid confrontation and flee the battlefield if they take damage or get hold of enough loot ",
"a flock of birds begin assaulting combatants with well aimed feces. ",
"A Tiefling scribe sits on the sidelines recording the battle. The scribe likes to critique the combatants",
"A cat chases a critter through the battlefield ",
"The fighting has attracted a group of bandits or raiders. They watch the fight with the intention of finishing off the winner to take all the spoils ",
"a characteristic of a party member reminds the adversary about something meaningful and he gets emotional. Effects of a calm emotions spell ",
"Somebody unequipped to fight charges in against the monster/enemy and presents more of a risk to themselves than whatever they are fighting ",
"A spellscroll from an adversary casts unexpectidly in their pocket!",
"A few rounds after dead, one of the adversaries rises as an undead",
"A devil reveals itself offering it's aid to the highest bidder (anything from gold to souls) ",
"A fae discovers the fight and begins playing tricks and casting spells on the combatants in an attempt to make the fight more interesting ",
"One of the enemies glasses fall of and they have the Blind affect for 1 turn ",
"An enemies bag falls over spilling 1d4 magic beans on the ground, which take root immediately. Roll on Bag of Beans table",
"Attacking the target will have major repercussions like starting a war. ",
"If killed the creature releases pheromones that cause all others of its kind to go into a berserker rage. ",
"Its a very tense situation between two or more groups. The situation requires deescalation. ",
"The area has very strict laws on violence (or at least killing). Anyone seen involved in a fight, even in self-defence, will be arrested and face life or the noose. ",
"The area is full of fragile expensive stuff. If anything breaks as a result of your fight, you will have to pay the bill.",
"The enemy has rigged some sort of death trap the characters must stop instead. Bomb, hidden hostage, etc",
"The enemy is not actually there, astral projection, hologram, illusion, messenger, etc",
"The enemy is using a hostage as a shield.",
"The enemy's blood is acidic, causing damage to equipment and body",
"If they enemy fails to report back home, a much larger force will come looking for them",
"A curse has linked you and the enemy. Any damage you inflict to the target you also receive in kind.",
"The area is holy ground. Killing anyone within the area will defile it, cursing you",
"The fight is happening on a ritual ground. If enough blood is spilled, then a demon will be summoned",
"The monster is actually just protecting its babies",
"The monster is actually a polymorphed person who can't control themselves and needs help",
"The monster is sacred to a local tribe, who will be very upset if it's killed",
"The enemy has some kind of deadman switch. Kill them and the whole place blows (or something else)",
"The enemy is infected with a disease. The more damage they take, the higher the chance of infection to players and area.",
"Barrel of potions that buff Strength, Dexterity, Health, give bonus actions, etc",
"Animated weapons sleeping around that can be convinced to help you or the enemy",
"Enemy has a baby held in a chest harness",
"Enemy is trying to read a powerfull spell scroll and will succeed after X turns",
"Enemy is trying to summon a powerful creature and will succeed after X turns",
"Enemy is adept at disarming and will take your weapons after disarmed",
"A sudden acid rain storm, forcing people to take cover ",
"Sudden heat wave requires everyone to not exert themselves too much",
"Corrosive mist causes weapons and armor to degrade unless covered up",
"Enemies can only see movement",
"Enemies can only see via smell",
"A massive hole in the middle, with unstable ground around it",
"Large cliffs with enchanted vines that pull creatures up them",
]