export default [
"Acid Vial",
"Alchemist Fire Flask",
"Alchemy Jug",
"Animal Treats",
"Backpack",
"Bag of Critters",
"Ball Bearings (100)",
"Ball",
"Basket",
"Pet Bird",
"Vial with blue liquid",
"Book",
"Boots of False Tracks",
"Breastplate Armor",
"Broken Dimensional Shackles",
"Brush",
"Candles (10)",
"Cape of Dashing",
"Cape",
"Pet Cat",
"Chain Mail Armor",
"Chain (15ft)",
"Chain Shirt Armor",
"Charlatan's Die",
"Cheese Cloth",
"Cloak of Billowing",
"Clockwork Amulet",
"Coffee Beans",
"Crowbar",
"Cursed Instrument",
"Cursed Pipe",
"Dagger",
"Dead Snake",
"Dice",
"Pet Dog",
"Dried Meat",
"Dust of Disappearance",
"Dust of Sneezing/Choking",
"Dye (vial)",
"Ear Plugs",
"Elemental Gem",
"Fishing Rod",
"Flute",
"Foreign Coins",
"Formal Document",
"Gemstone",
"Glue",
"Hair Brush that Kills Hair",
"Hairbrush",
"Half Plate Armor",
"Crimson Health Gem",
"Hemp Rope (30ft)",
"Herbs",
"Hide Armor",
"Honey",
"Horn (hollow)",
"Hourglass",
"Immovable Rod",
"Indica Berries",
"Ink and Pen",
"Keoghtom's Ointment",
"Lantern",
"Leather Armor",
"Letter",
"Local Map",
"Locket with Picture",
"Lockpick",
"Love Potion",
"Lute",
"Magnifying Glass",
"Makeup",
"Small mirror",
"Mortar and Pestle",
"Mushrooms",
"Mystery Key",
"Nails",
"Oats",
"Oil (flask)",
"Padded Armor",
"Painting (scroll case)",
"Pipe",
"Plate Armor",
"Playing Cards",
"Pliers",
"Poll of Collapsing",
"Portable Hole",
"Pot of Awakening",
"Potion of Flight",
"Potion of Growth",
"Potion of Healing",
"Potion of Heroism",
"Potion of Mind Reading",
"Potion of Stone Self",
"Pure Fairy Dust",
"Self-Regenerating Cabbage",
"Ring Mail Armor",
"Sativa Berries",
"Scale Mail Armor",
"Seal Stamp",
"Shield",
"Shortsword",
"Shovel",
"Silk Rope (30ft)",
"Sleep Mask",
"Soap",
"Sovereign Glue",
"Spell Scroll (weak)",
"Spell Scroll (strong)",
"Splint Armor",
"Studded Leather Armor",
"Talking Doll ",
"Tankard of Sobriety",
"Tinderbox",
"Tobacco",
"Treasure Map",
"Tweezers",
"Twitch Thorns",
"Unbreakable Rope (3 feet)",
"Undulling Knife",
"Impure Fairy Dust",
"Empty Vials",
"Wand of Secrets",
"Wand of Smiles",
"Waterskin",
"Whistle",
"Wind Fan",
"Wine Corks",
"Wine",
"Yarn",
"Yeast",
"Tooth",
"Game piece",
"Towl",
"Pearl",
"Spices",
"Incense",
"Sundial watch",
"Fried bug",
"Poison (weak)",
"Poison (strong)",
"Arrow of sure thing",
"Love Potion",
"Rope Ladder",
"Magic Mirror",
"Skeleton Key",
"Crystal Ball",
"Acorn Necklace",
"Potion of Invisibility",
"Vampire Fang",
"Chalk",
"Wooden Amulet",
"Sacred Tome",
"Dragon Scale",
"Map of Hidden Passages",
"Iron Rations",
"Vial of Blood",
"Gilded Dagger",
"Silver Spoon",
"Quill",
"Broken Sword",
"Runestone",
"Witch’s Broom",
"Firestarter",
"Spellbook",
"Silver Ring",
"Chain of Command",
"Magic Carpet",
"Animal Bone",
"Ancient Coin",
"Moonstone",
"Grimoire",
"Glass Orb",
"Silver Flute",
"Magic Feather",
"Bag of Holding",
"Brass Key",
"Portable Altar",
"Thieves’ Tools",
"Ornate Chalice",
"Crystal Shard",
"Enchanted Gloves",
"Ring of Protection",
"Vial of Eternal Youth",
"Elven Cloak",
"Sunstone",
"Healing Salve",
"Trick Coin",
"Silver Locket",
"Gold Leaf",
"Briar Patch",
"Spell Components",
"Phoenix Feather",
"Moonlit Dagger",
"Wind Chimes",
"Dragon's Tooth",
"Silver Lining",
"Map of Stars",
"Sack of Seeds",
"Troll’s Toenail",
"Unicorn Horn",
"Shiny Pebble",
"Water Breathing Gem",
"Horn of Fog",
"Boots of Speed",
"Miniature Statue",
"Wormwood Sprig",
"Climbing Gloves",
"Etherstone",
"Enchanted Key",
"Healing Herb",
"Mirror of Reflection",
"Drake’s Eye",
"Cursebreaker Talisman",
"Golden Feather",
"Vial of Starlight",
"Treasure Chest",
"Jar of Fireflies",
"Feathered Quill",
"Boots of Leaping",
"Small Lantern",
"Magical Dust",
"Cloak of Shadows",
"Fiery Stone",
"Crystal Phial",
"Snake Venom",
"Thunderstone",
"Arcane Focus",
"Elven Bread",
"Familiar's Bell",
"Potion of Luck",
"Rations",
"Rope",
"Water Skin",
"Flint and Steel",
"Wooden Shield",
"Blanket",
"Campfire Kit",
"Cloth Pouch",
"Whetstone",
"Scalpel",
"Bread",
"Pitchfork",
"Wooden Spoon",
"Tin Cup",
"Bucket",
"Jar of Honey",
"Spade",
"Fishing Net",
"Map",
"Herbal Tea",
"Antique Key",
"String",
"Coin Purse",
"Handkerchief",
"Leather Gloves",
"Charcoal",
"Chisel",
"Soapstone",
"Ball of Twine",
"Sling",
"Patch Kit",
"Cloth Bandages",
"Wooden Bowl",
"Quiver",
"Shovel",
"Slate",
"Candle Holder",
"Scrap of Cloth",
"Stone",
"Tin Lantern",
"Wooden Box",
"Bundle of Sticks",
"Small Jar",
"Wooden Carving",
"Notepad",
"Whittling Knife",
"Corked Bottle",
"Twig",
"Pack of Cards",
"Salt",
"Soap Bar",
"Scrap Paper",
"Spool of Thread",
"Tinderbox",
"Pack of Herbs",
"Clay Pot",
"Coil of Rope",
"Matches",
"Sack of Grain",
"Old Shoe",
"Rain Poncho",
"Wooden Chest",
"Lantern Oil",
"Paper Fan",
"Fur Pelt",
"Leather Strap",
"Stone Jar",
"Peasant's Hat",
"Wooden Tankard",
"Piece of Coal",
"Traveling Cloak",
"Small Hammer",
"Scarf",
"Fishing Hook",
"Beads",
"Twisted Metal",
"Old Coin",
"Torch",
"Bell",
"Wooden Plate",
"Chalk Stick",
"Patchwork Quilt",
"Pet Rock",
"Piece of String",
"Glass Bottle",
"Wooden Comb",
"Scents",
"Clay Figurine",
"Teacup",
"Bowl of Fruit",
"Leather Boots",
"Pocket Watch",
"Paper Scroll",
"Pin",
"Raincoat",
"Apple",
"Block of Cheese"
]