export default ["Fire Elemental",
"Shadow Cult",
"Celestial Order",
"Moon Goddess",
"Vampire Lord",
"Druid Circle",
"Thief Guild",
"Arcane Scholar",
"Undead Legion",
"Demon Prince",
"Beast Pack",
"Sea Serpent",
"Fey Queen",
"Ironclad King",
"Dragon Knight",
"Warlock Pact",
"Fallen Angel",
"Necromancer Guild",
"Sun Priestess",
"Storm Giants",
"Earth Titan",
"Mercenary Band",
"Spirit Guardian",
"Orc Chieftain",
"Goblin Horde",
"Elven Council",
"Bandit King",
"Haunted Forest",
"Blood Coven",
"Sky Pirates",
"Ancient Oracle",
"Swamp Witch",
"Thunder Beast",
"Demon Hunter",
"Shadow Assassin",
"Lightning Dragon",
"Forest Spirits",
"Sea Witch",
"Holy Inquisition",
"Pirate Queen",
"Elemental Lord",
"Iron Guild",
"Moon Wolf",
"Cursed King",
"Frozen Warden",
"Dark Sorcerer",
"Abyssal Leviathan",
"Royal Family",
"Sacred Order",
"War Machine",
"Rival Merchants",
"Neighboring Town",
"Family Feud",
"Political Faction",
"Religious Sect",
"Trade Union",
"Old Friends",
"Business Partners",
"School Rival",
"Landowner Dispute",
"Wealthy Patron",
"Local Government",
"Charity Organization",
"Civic Leader",
"Farming Guild",
"Construction Crew",
"Union Workers",
"Childhood Rival",
"Military Officer",
"Street Gang",
"Wealthy Investor",
"Adventurer Party",
"Noble Family",
"Town Mayor",
"Public Defender",
"Police Force",
"News Media",
"Legal Counsel",
"Medical Staff",
"Bank Manager",
"Court Judge",
"City Council",
"Merchant Guild",
"Tavern Owner",
"Innkeeper",
"Shopkeeper Dispute",
"Local Hero",
"Animal Shelter",
"Park Rangers",
"Environmental Group",
"Protest Movement",
"School Bully",
"Book Club",
"Volunteer Group",
"Family Business",
"Construction Firm",
"Neighborhood Watch",
"Religious Leader",
"Parent Group",
"Retirement Home",
"Rivalry",
"Greed",
"Religion",
"Power",
"Ambition",
"Justice",
"Revenge",
"Betrayal",
"Corruption",
"Freedom",
"Fame",
"Loyalty",
"Security",
"Knowledge",
"Territory",
"Trust",
"Honor",
"Wealth",
"Loyalty",
"Deception",
"Fame",
"Influence",
"Survival",
"Justice",
"Control",
"Vengeance",
"Family",
"Tradition",
"Technology",
"Fame",
"Nature",
"Conflict",
"Secrets",
"Chaos",
"Love",
"Progress",
"Order",
"Memory",
"Innovation",
"Rebellion",
"Crime",
"Protection",
"Legacy",
"Equality",
"Independence",
"Safety",
"Revenge",
"Ambition",
"Respect",
"Leadership",
"Ancient Curse",
"Street Rival",
"Lost Love",
"Rival Kingdom",
"Rogue Element",
"Ghostly Apparition",
"Dark Secret",
"Cursed Land",
"Ancient Artifacts",
"Mastermind Plot",
"Ancient Beast",
"Demon Hunter",
"Lone Wolf",
"Storm Witch",
"Fire Drake",
"Blood Beast",
"Frost Giant",
"Shadow Serpent",
"Lich King",
"Stone Golem",
"Void Spider",
"Death Knight",
"Hellhound Pack",
"Thunder Wolf",
"Abyssal Leviathan",
"Wraith Lord",
"Ironclad Minotaur",
"Bone Golem",
"Doomslayer Demon",
"Serpent Queen",
"Venom Manticore",
"Chaos Dragon",
"Phantom Knight",
"Skull Cyclops",
"Dire Bear",
"Blood Kraken",
"Frost Troll",
"Nightmare Beast",
"Bone Wyvern",
"Stone Basilisk",
"Ember Wraith",
"Thunder Titan",
"Plague Rat",
"Flesh Golem",
"Mutant Spider",
"Inferno Serpent",
"Crystal Hydra",
"Blood Demon",
"Iron Beast",
"Storm Golem",
"Ice Wyrm",
"Lava Golem",
"Phantom Wolf",
"Acid Fiend",
"Swamp Troll",
"Sky Kraken",
"Sand Demon",
"Dread Beast",
"Abyssal Fiend",
"Shrieking Wraith",
"Steel Gargoyle",
"Venom Hydra",
"Infernal Wyvern",
"Royal Heir",
"Rebel Leader",
"Merchant Cartel",
"Noble House",
"Military General",
"Secret Police",
"Spy Network",
"Diplomatic Envoy",
"Political Advisor",
"Legal Counsel",
"Religious Faction",
"Foreign Ambassador",
"Assassin Guild",
"Trade Routes",
"Distant Colony",
"Tax Collector",
"Power Broker",
"Court Jester",
"Economic Alliance",
"Military Coup",
"Rebel Cell",
"Guild Leader",
"Peasant Revolt",
"Pirate Fleet",
"Secret Treaty",
"Intelligence Officer",
"Political Marriage",
"Underground Movement",
"Trade War",
"Heir Apparent",
"Nobility Rivalry",
"Foreign Empire",
"Princely Claim",
"Spy Master",
"Diplomatic Scandal",
"Election Campaign",
"City Council",
"Urban Riots",
"Feudal Baron",
"Forbidden Alliance",
"War Profit",
"Diplomatic Betrayal",
"Land Reforms",
"Reformed Monarchy",
"Aristocratic Whispers",
"Power Struggle",
"Insurrection Leader",
"Tax Evasion",
"Border Dispute",
"Rival Dynasty",
"Boss",
"Best Friend",
"Ex-Spouse",
"Neighbor",
"Co-worker",
"Local Mafia",
"Guards",
"Sibling",
"Parent",
"Mentor",
"Apprentice",
"Politician",
"Religious Leader",
"Government Official",
"Union Leader",
"Journalist",
"Business Owner",
"Community Leader",
"Neighborhood Watch",
]