export default ["Shadow Cloak",
"Phoenix Feather",
"Diamond Blade",
"Rune Stone",
"Frost Ring",
"Dragon Scale",
"Elven Bow",
"Sun Amulet",
"Ghost Lantern",
"Moonstone Pendant",
"Healing Staff",
"Arcane Tome",
"Fire Gauntlets",
"Silver Chalice",
"Storm Gem",
"Crystal Dagger",
"Iron Boots",
"Soul Mirror",
"Celestial Armor",
"Lightning Rod",
"Enchanted Necklace",
"Time Crystal",
"Wind Fan",
"Life Crystal",
"Shadow Blade",
"Mystic Orb",
"Cursed Helmet",
"Eternal Torch",
"Celestial Crown",
"Phantom Gloves",
"Bloodstone Ring",
"Ice Scepter",
"Night Cloak",
"Elemental Staff",
"Obsidian Blade",
"Specter Mask",
"Rune Bracelet",
"Sunshield Cape",
"Faerie Dust",
"Emberstone Ring",
"Arcane Lantern",
"Gravity Boots",
"Beaststone Collar",
"Serpent Scale",
"Moonlit Talisman",
"Starfire Wand",
"Wyrmhide Cloak",
"Crystal Shield",
"Voidstone Amulet",
"Thunder Horn",
"Arcane Boots",
"Dragon Fang",
"Storm Blade",
"Inferno Ring",
"Mystic Compass",
"Frost Mantle",
"Ember Necklace",
"Moon Veil",
"Spirit Talisman",
"Shadow Sigil",
"Celestial Tome",
"Vortex Cloak",
"Firestone Amulet",
"Astral Glove",
"Void Dagger",
"Sunstone Staff",
"Crystal Flute",
"Thunderstone Pendant",
"Dreamcatcher Charm",
"Ghostly Shroud",
"Ironwood Blade",
"Sapphire Crown",
"Rune Band",
"Nightshade Cloak",
"Fae Lantern",
"Bloodmoon Shield",
"Starshard Ring",
"Luminous Gem",
"Obsidian Pendant",
"Frostbite Sash",
"Soulstone Necklace",
"Poison Fang",
"Crystal Wings",
"Spectral Blade",
"Sunfire Collar",
"Dragonheart Armor",
"Spiritstone Ring",
"Phantom Talisman",
"Eternal Tome",
"Nightfall Gauntlets",
"Infernal Armor",
"Bloodvine Boots",
"Ether Wand",
"Dreamstone Mirror",
"Ember Gauntlets",
"Stormsoul Cloak",
"Ironheart Talisman",
"Moonfire Mask",
"Lightning Crown",
"Phoenix Tear",
"Thunderclap Boots",
"Soulflame Blade",
"Frostflare Ring",
"Arcane Shield",
"Wyrmstone Pendant",
"Crystal Horn",
"Starblaze Amulet",
"Voidstone Shield",
"Faerie Crown",
"Elemental Gem",
"Darkheart Blade",
"Gilded Scepter",
"Bloodthorn Necklace",
"Steelleaf Cloak",
"Frosted Boots",
"Emberstone Ring",
"Starfire Amulet",
"Twilight Orb",
"Ghostfire Blade",
"Moonshadow Cloak",
"Infernal Talisman",
"Celestial Sash",
"Lightstone Boots",
"Dragonfire Crown",
"Arcane Lantern",
"Nightshade Ring",
"Crystal Earring",
"Shimmering Dagger",
"Thunderstrike Pendant",
"Stormstone Bracelet",
"Rune Sash",
"Firebrand Amulet",
"Ashen Cloak",
"Stormshard Sword",
"Phantom Bracelet",
"Emberstone Cloak",
"Shining Gauntlets",
"Twilight Talisman",
"Dragonblood Ring",
"Icebrand Wand",
"Spiritwood Mask",
"Shadowstone Amulet",
"Dawnshard Armor",
"Frostshard Blade",
"Sunflare Ring",
"Moonlit Gem",
"Crystal Talisman",
"Stormcaller Staff",
"Etherstone Cloak",
"Rune Dagger",
"Celestial Blade",
"Shadow Cloak",
"Thunder Gauntlets",
"Firebrand Shield",
"Eclipse Crown",
"Frostbite Dagger",
"Dragonheart Amulet",
"Stormwind Cloak",
"Soulfire Blade",
"Crystal Heart",
"Timeweaver Ring",
"Moonstone Talisman",
"Emberstone Scepter",
"Obsidian Ring",
"Arcane Cloak",
"Runehammer Mace",
"Starfire Pendant",
"Lightning Talisman",
"Phantom Cloak",
"Ghoststone Ring",
"Voidstone Sword",
"Sunflare Boots",
"Faerie Blade",
"Dragonwing Cape",
"Frosthelm Crown",
"Nightshade Blade",
"Soulstone Ring",
"Celestial Bow",
"Vortex Crystal",
"Ashen Mask",
"Starshard Talisman",
"Bloodstone Blade",
"Stormcaller Boots",
"Wraithfang Cloak",
"Firelight Orb",
"Crystal Shield",
"Moonlit Blade",
"Arcane Charm",
"Frostweb Cloak",
"Lightning Ring",
"Dragonclaw Gloves",
"Soulshard Blade",
"Venomous Fangs",
"Phantom Staff",
"Windweaver Boots",
"Thunderstrike Sword",
"Emberstone Ring",
"Iceheart Gloves",
"Serpentfang Cloak",
"Sunstone Dagger",
"Shadowstone Staff",
"Arcane Bracers",
"Celestial Shield",
"Infernal Ring",
"Faerie Dust",
"Midnight Amulet",
"Stormstone Crown",
"Bloodbane Cloak",
"Shadowflare Dagger",
"Moonfire Ring",
"Dragonbone Scepter",
"Celestial Wings",
"Emberstone Boots",
"Starforge Blade",
"Icewind Shield",
"Lightning Fang",
"Eternal Lantern",
"Nightwind Boots",
"Rune Cloak",
"Dreamweaver Mask",
"Shadowfang Dagger",
"Radiant Gloves",
"Bloodveil Amulet",
"Starshard Cloak",
"Firestorm Scepter",
"Obsidian Boots",
"Dragonstone Ring",
"Spectral Lantern",
"Spiritfire Wand",
"Emberstorm Shield",
"Nightshade Amulet",
"Voidclaw Dagger",
"Moonshard Ring",
"Stormstrike Bracers",
"Sunstone Wand",
"Crystal Staff",
"Thunderstone Gauntlets",
"Soulflame Mask",
"Icebound Cloak",
"Dragonflame Ring",
"Arcane Talisman",
"Bloodthorn Boots",
"Celestial Dagger",
"Specter Crown",
"Firewing Amulet",
"Froststone Sword",
"Thunderclap Boots",
"Voidstone Talisman",
"Emberveil Mask",
"Soulstone Blade",
"A Night's Rest",
"Safe Passage",
"Free Meal",
"Friendly Advice",
"Temporary Shelter",
"A Helpful Map",
"Free Lodging",
"Local Favor",
"A Small Coin Pouch",
"A Guided Step",
"Extra Rations",
"A Warm Drink",
"A Quiet Spot",
"A Simple Blessing",
"A Kind Word",
"A Shared Song",
"A Handful of Herbs",
"A New Friend",
"Temporary Refuge",
"A Well-Timed Wind",
"A Helpful Introduction",
"An Old Story",
"A Comfortable Blanket",
"A Shared Fire",
"A Cheerful Smile",
"A Safe House",
"A Healing Salve",
"A Kind Gesture",
"Helpful Directions",
"A Clear Path",
"Simple Guidance",
"A Clean Bandage",
"A Drink of Water",
"A Hand to Hold",
"A Fresh Start",
"A Quiet Moment",
"A Friendly Face",
"A Temporary Discount",
"A Free Ride",
"A New Skill",
"A Task Completed",
"A Happy Memory",
"A Moment of Peace",
"A Chance to Rest",
"A Warm Coat",
"A Lullaby Song",
"A Quick Escape",
"A Simple Tool",
"A Small Token",
"A Safe Haven",
"A Favorable Deal",
"Temporary Protection",
"Safe Passage",
"Strong Ally",
"Blessing of Speed",
"Trusted Companion",
"A New Reputation",
"Enchanted Guidance",
"Temporary Immunity",
"Favor of the Gods",
"Swift Recovery",
"Lifting of a Curse",
"Allies in the Shadows",
"Knowledge of the Unknown",
"Restorative Healing",
"Access to Hidden Paths",
"Temporary Resistance",
"Cleansing of the Soul",
"Swift Winds",
"Boosted Strength",
"Shield of Honor",
"Blessing of Stealth",
"Word of Recommendation",
"Increased Luck",
"Increased Charisma",
"Blessing of Courage",
"Temporary Strength",
"A Trusted Guide",
"Voice of Authority",
"An Oath of Loyalty",
"Favor of the Forest",
"Blessing of the Moon",
"A Friend in High Places",
"Protection from Harm",
"Blessed Hands",
"Magic of the Earth",
"Blessing of Protection",
"Favor of the Fire",
"Gold Pouch",
"Platinum Coins",
"Pile of Gems",
"Silver Ingots",
"Treasure Chest",
"Rare Artifacts",
"Bag of Coins",
"Pouch of Rubies",
"Gold Bars",
"Purse of Diamonds",
"Merchant’s Favor",
"Any favor",
"Vault Key",
"Estate Inheritance",
"Share of Spoils",
"Jewel-Encrusted Ring",
"Gemstone Necklace",
"Diamond-Studded Brooch",
"Treasure Map",
"Rare Metals",
"Rare Art",
"Platinum Bar",
"Hoard of Coins",
"Gem-Encrusted Pendant",
"Silver Crown",
"Merchant’s Discount",
"Training",
"Rare Coins",
]