export default ["Assassination",
"Escort",
"Retrieval",
"Delivery",
"Exploration",
"Investigation",
"Rescue",
"Defense",
"Collection",
"Heist",
"Hunting",
"Bounty",
"Puzzle",
"Sabotage",
"Diplomacy",
"Assassination",
"Escort",
"Retrieval",
"Delivery",
"Exploration",
"Investigation",
"Rescue",
"Defense",
"Collection",
"Heist",
"Hunting",
"Bounty",
"Puzzle",
"Sabotage",
"Diplomacy",
"Liberation",
"Protection",
"Stealth",
"Combat",
"Crafting",
"Conquest",
"Conspiracy",
"Survival",
"Infiltration",
"Siege",
"Spy",
"Challenge",
"Ritual",
"Investigation",
"Research",
"Negotiation",
"Exploration",
"Training",
"Rebellion",
"Invasion",
"Discovery",
"Rescue",
"Sabotage",
"Recovery",
"Defense",
"Reclamation",
"Hunt",
"Cure",
"Extermination",
"Protection",
"Taming",
"Construction",
"Reconstruction",
"Retaliation",
"Exile",
"Plague",
"Rebirth",
"Suppression",
"Trap",
"Confrontation",
"Relic",
"Reconstruction",
"Extraction",
"Defense",
"Detour",
"Subterfuge",
"Betrayal",
"Redemption",
"Scouting",
"Trial",
"Conviction",
"Sacrifice",
"Offering",
"Tournament",
"Punishment",
"Reprisal",
"Convoy",
"Cleansing",
"Survival",
"Resurrection",
"Challenge",
"Cleansing",
"Test",
"Ritual",
"Discovery",
"Diagnosis",
"Escape",
"Reconciliation",
"Framing",
"Investigation",
"Outlaw",
"Discovery",
"Delivery",
"Intervention",
"Retribution",
"Scavenging",
"Dismantle",
"Exploration",
"Fortification",
"Siege",
"Exorcism",
"Alchemy",
"Espionage",
"Assay",
"Testing",
"Negotiation",
"Disguise",
"Famine",
"Relocation",
"Reassignment",
"Tribute",
"Reconstruction",
"Suppression",
"Sabotage",
"Reclamation",
"Counterattack",
"Domination",
"Blessing",
"Collusion",
"Ritual",
"Seclusion",
"Thievery",
"Repentance",
"Capture",
"Repossession",
"Awakening",
"Convergence",
"Tracking",
"Overthrow",
"Summoning",
"Divination",
"Cursebreaking",
"Necromancy",
"Hexbreaking",
"Warding",
"Claiming Territory",
"Protecting Relics",
"Recovering Artifacts",
"Building Stronghold",
"Fortifying Walls",
"Clearing Caves",
"Gathering Herbs",
"Crafting Weapons",
"Finding Lost City",
"Defeating Beasts",
"Raising Army",
"Hunting Legendary Creature",
"Reclaiming Land",
"Investigating Ruins",
"Tracking Enemy",
"Destroying Artifacts",
"Assisting Villagers",
"Establishing Trade",
"Securing Passage",
"Taking Hostages",
"Reconstructing Village",
"Slaying Monsters",
"Crafting Potions",
"Harvesting Resources",
"Finding Sanctuary",
"Escorting Caravan",
"Uncovering Secrets",
"Defending Village",
"Establishing Diplomacy",
"Delivering Message",
"Opening Ancient Tomb",
"Protecting Princess",
"Breaking Siege",
"Reviving Spirit",
"Eradicating Plague",
"Breaking Curse",
"Securing Vault",
"Exploring Dungeons",
"Convincing Faction",
"Ransacking Fortress",
"Reuniting Families",
"Summoning Creature",
"Assisting in Battle",
"Destroying Corruption",
"Sealing Portal",
"Safeguarding Treasure",
"Negotiating Peace",
"Securing Borders",
"Disarming Trap",
"Finding Heir",
"Uniting Factions",
"Defending Outpost",
"Exploring Wilderness",
"Breaking an Alliance",
"Hunting for Bounty",
"Rebuilding Bridge",
"Unlocking Vault",
"Taming Beast",
"Finding Lost Heirloom",
"Reclaiming Fortress",
"Investigating Disappearances",
"Escorting Merchant",
"Gathering Supplies",
"Stopping Ritual",
"Disrupting Cult",
"Assisting Rebels",
"Destroying Invasion Force",
"Recovering Magic Item",
"Seizing Control",
"Purging Undead",
"Disbanding Cult",
"Delivering Supplies",
"Breaking Prisoners Free",
"Slaying Giant",
"Clearing Forest",
"Overthrowing Tyrant",
"Investigating Poisoning",
"Destroying Infected Area",
"Cleansing Haunted Grounds",
"Uncovering Betrayal",
"Delivering Artifact",
"Negotiating Tribute",
"Taming Magical Creature",
"Hunting for Treasure",
"Securing Key",
"Establishing Settlement",
"Finding Safe Haven",
"Rebuilding Temple",
"Breaking Magical Barrier",
"Fulfilling Prophecy",
"Protecting Sacred Ground",
"Escaping Dungeon",
"Confronting Warlord",
"Tracking Down Thief",
"Setting Traps",
"Hunting for Ingredients",
"Exploring Ancient Ruins",
"Overcoming Trials",
"Breaking Into Stronghold",
"Rescuing Prisoner",
"Clearing Haunted Forest",
"Forging Alliance",
"Investigating Ancient Curse",
"Protecting Caravan",
"Stopping Ritual Sacrifice",
"Destroying Dark Artefacts",
"Gathering Magical Essence",
"Defeating a Dragon",
"Breaking Siege",
"Capturing Bandits",
"Seeking Redemption",
"Tracking Rare Beast",
"Recovering Lost Knowledge",
"Defending Relic",
"Securing Escape Route",
"Stopping Plague Outbreak",
"Revealing Hidden Passage",
"Securing Spells",
"Protecting Sacred Artifact",
"Exterminating Demons",
"Healing the Sick",
"Seeking Lost Kingdom",
"Restoring Royalty",
"Reclaiming Stolen Treasure",
"Gathering War Intel",
"Solving Ancient Puzzle",
"Breaking Magical Curse",
"Reversing Time Magic",
"Strengthening Defenses",
"Rebuilding Lighthouse",
"Finding Ancient Weapon",
"Sealing Forbidden Magic",
"Stopping Magical Experiment",
"Recovering Stolen Relic",
"Breaking Enemy Lines",
"Stopping Necromancer",
"Finding Hidden Heir",
"Defending Magical Source",
"Delivering Rare Item",
"Investigating Disappearances",
"Breaking Into Vault",
"Stopping Dark Sorcery",
"Escorting Noble",
"Protecting Mage Guild",
"Reclaiming Artifact",
"Neutralizing Poison",
"Unveiling Hidden Truth",
"Securing Safe Passage",
"Uniting Warring Clans",
"Disrupting Rituals",
"Recovering Stolen Artifacts",
"Hunting for Rare Herbs",
"Investigating Ancient Ruins",
"Rescuing Captured Allies",
"Defeating Rival Sorcerer",
"Protecting Sacred Grove",
"Rebuilding Port",
"Breaking Into Dungeon",
"Finding Lost Treasure Map",
"Neutralizing Bandit Leader",
"Gathering Ritual Components",
"Searching for Lost Tome",
"Reuniting Lost Lovers",
"Securing Magical Relic",
"Destroying a Portal",
"Searching for Legendary Beast",
"Reclaiming Ancient Scroll",
"Expelling Evil Spirit",
"Securing Passage through Mountains",
"Stopping a War",
"Delivering Royal Decree",
"Rescuing Prisoners from Dungeon",
"Finding Hidden Temple",
"Investigating Conspiracy",
"Securing Powerful Magic",
"Rebuilding Village Walls",
"Assisting in Ritual Ceremony",
"Disrupting Enemy Supply Lines",
"Finding Heir’s Identity",
"Protecting the Last of a Species",
"Slaying a Hydra",
"Breaking a Siege",
"Securing Trade Route",
"Investigating Haunted Castle",
"Reestablishing Order",
"Protecting Ancient Library",
"Mapping Uncharted Lands",
"Recovering Stolen Documents",
"Challenging a Champion",
"Solving a Riddle",
"Uncovering Hidden Vault",
"Stopping a Dangerous Cult",
"Defending Wizard Tower",
"Assisting a Fledgling Mage",
"Securing an Ancient Weapon",
"Reopening Abandoned Mine",
"Defeating a Tyrant",
"Exposing a Betrayal",
"Forging a Magic Item",
"Breaking Free from Enchantment",
"Assassinating a Rival",
"Exposing a Traitor",
"Securing an Alliance",
"Sabotaging Diplomacy",
"Investigating Corruption",
"Manipulating Factions",
"Infiltrating Court",
"Blackmailing Noble",
"Uncovering Espionage",
"Protecting Royal Secret",
"Framing Political Enemy",
"Spreading Propaganda",
"Negotiating Peace",
"Exposing Scandal",
"Betraying an Ally",
"Protecting the Throne",
"Spying on Court",
"Securing Loyalty",
"Disrupting a Coup",
"Smuggling Information",
"Inciting Rebellion",
"Reversing a Decision",
"Securing a Marriage",
"Raising Public Support",
"Dealing with Extortion",
"nfluencing a Council",
"Engineering a Betrayal",
"Spreading Rumors",
"Protecting a Secret Affair",
"Blackmailing a Noble",
"Manipulating a Power Struggle",
"Turning Allies Against Each Other",
"Revealing Hidden Loyalties",
"Arranging a Favor",
"Sabotaging a Marriage",
"Orchestrating a Scandal",
"Securing a Favorable Vote",
"Provoking a Duel",
]